/**
 * @file middleware.ts
 * @description Security middleware for API protection
 * @auto-generated by todo-automation
 */

import { createHash, randomBytes } from 'crypto';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface RateLimitConfig {
  windowMs: number;
  maxRequests: number;
  keyGenerator?: (req: Request) => string;
  skipFailedRequests?: boolean;
  skipSuccessfulRequests?: boolean;
}

export interface RateLimitResult {
  allowed: boolean;
  remaining: number;
  resetTime: number;
  retryAfter?: number;
}

interface RateLimitEntry {
  count: number;
  resetTime: number;
}

export interface CSRFConfig {
  tokenLength?: number;
  cookieName?: string;
  headerName?: string;
  secret?: string;
}

export interface SecurityHeaders {
  'Content-Security-Policy': string;
  'X-Content-Type-Options': string;
  'X-Frame-Options': string;
  'X-XSS-Protection': string;
  'Referrer-Policy': string;
  'Strict-Transport-Security': string;
  'Permissions-Policy': string;
}

// ═══════════════════════════════════════════════════════════════════════════
// Rate Limiter
// ═══════════════════════════════════════════════════════════════════════════

export class RateLimiter {
  private store: Map<string, RateLimitEntry> = new Map();
  private config: Required<RateLimitConfig>;
  private cleanupInterval: NodeJS.Timeout | null = null;

  constructor(config: RateLimitConfig) {
    this.config = {
      windowMs: config.windowMs || 60000,
      maxRequests: config.maxRequests || 100,
      keyGenerator: config.keyGenerator || this.defaultKeyGenerator,
      skipFailedRequests: config.skipFailedRequests || false,
      skipSuccessfulRequests: config.skipSuccessfulRequests || false,
    };

    // Cleanup expired entries every minute
    this.cleanupInterval = setInterval(() => this.cleanup(), 60000);
  }

  private defaultKeyGenerator(req: Request): string {
    // Try to get IP from headers, fall back to a random ID
    const forwarded = req.headers.get('x-forwarded-for');
    const realIp = req.headers.get('x-real-ip');
    return forwarded?.split(',')[0]?.trim() || realIp || 'unknown';
  }

  /**
   * Check if request is allowed
   */
  check(key: string): RateLimitResult {
    const now = Date.now();
    const entry = this.store.get(key);

    if (!entry || now > entry.resetTime) {
      // New window
      this.store.set(key, {
        count: 1,
        resetTime: now + this.config.windowMs,
      });

      return {
        allowed: true,
        remaining: this.config.maxRequests - 1,
        resetTime: now + this.config.windowMs,
      };
    }

    if (entry.count >= this.config.maxRequests) {
      return {
        allowed: false,
        remaining: 0,
        resetTime: entry.resetTime,
        retryAfter: Math.ceil((entry.resetTime - now) / 1000),
      };
    }

    entry.count++;
    return {
      allowed: true,
      remaining: this.config.maxRequests - entry.count,
      resetTime: entry.resetTime,
    };
  }

  /**
   * Middleware function for HTTP servers
   */
  middleware() {
    return async (req: Request): Promise<RateLimitResult> => {
      const key = this.config.keyGenerator(req);
      return this.check(key);
    };
  }

  /**
   * Reset limit for a key
   */
  reset(key: string): void {
    this.store.delete(key);
  }

  /**
   * Cleanup expired entries
   */
  private cleanup(): void {
    const now = Date.now();
    for (const [key, entry] of this.store.entries()) {
      if (now > entry.resetTime) {
        this.store.delete(key);
      }
    }
  }

  /**
   * Destroy the rate limiter
   */
  destroy(): void {
    if (this.cleanupInterval) {
      clearInterval(this.cleanupInterval);
    }
    this.store.clear();
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// CSRF Protection
// ═══════════════════════════════════════════════════════════════════════════

export class CSRFProtection {
  private config: Required<CSRFConfig>;

  constructor(config?: CSRFConfig) {
    this.config = {
      tokenLength: config?.tokenLength || 32,
      cookieName: config?.cookieName || 'csrf_token',
      headerName: config?.headerName || 'x-csrf-token',
      secret: config?.secret || randomBytes(32).toString('hex'),
    };
  }

  /**
   * Generate a new CSRF token
   */
  generateToken(sessionId?: string): string {
    const random = randomBytes(this.config.tokenLength).toString('hex');
    const data = sessionId ? `${random}:${sessionId}` : random;
    const signature = this.sign(data);
    return `${data}.${signature}`;
  }

  /**
   * Verify a CSRF token
   */
  verifyToken(token: string, sessionId?: string): boolean {
    try {
      const [data, signature] = token.split('.');
      
      if (!data || !signature) {
        return false;
      }

      // Verify signature
      const expectedSignature = this.sign(data);
      if (!this.timingSafeEqual(signature, expectedSignature)) {
        return false;
      }

      // If session ID is required, verify it matches
      if (sessionId) {
        const [, tokenSessionId] = data.split(':');
        return tokenSessionId === sessionId;
      }

      return true;
    } catch {
      return false;
    }
  }

  private sign(data: string): string {
    return createHash('sha256')
      .update(`${data}:${this.config.secret}`)
      .digest('hex')
      .slice(0, 32);
  }

  private timingSafeEqual(a: string, b: string): boolean {
    if (a.length !== b.length) return false;
    let result = 0;
    for (let i = 0; i < a.length; i++) {
      result |= a.charCodeAt(i) ^ b.charCodeAt(i);
    }
    return result === 0;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Security Headers
// ═══════════════════════════════════════════════════════════════════════════

export function getSecurityHeaders(options?: {
  allowFrameFrom?: string[];
  allowScriptsFrom?: string[];
  reportUri?: string;
}): SecurityHeaders {
  const frameAncestors = options?.allowFrameFrom?.length
    ? options.allowFrameFrom.join(' ')
    : "'none'";

  const scriptSrc = options?.allowScriptsFrom?.length
    ? `'self' ${options.allowScriptsFrom.join(' ')}`
    : "'self'";

  return {
    'Content-Security-Policy': [
      `default-src 'self'`,
      `script-src ${scriptSrc}`,
      `style-src 'self' 'unsafe-inline'`,
      `img-src 'self' data: https:`,
      `font-src 'self'`,
      `connect-src 'self' https:`,
      `frame-ancestors ${frameAncestors}`,
      options?.reportUri ? `report-uri ${options.reportUri}` : '',
    ].filter(Boolean).join('; '),
    'X-Content-Type-Options': 'nosniff',
    'X-Frame-Options': 'DENY',
    'X-XSS-Protection': '1; mode=block',
    'Referrer-Policy': 'strict-origin-when-cross-origin',
    'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
    'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Input Validation
// ═══════════════════════════════════════════════════════════════════════════

export const validators = {
  isAddress: (value: string): boolean => {
    return /^0x[a-fA-F0-9]{40}$/.test(value);
  },

  isTxHash: (value: string): boolean => {
    return /^0x[a-fA-F0-9]{64}$/.test(value);
  },

  isHex: (value: string): boolean => {
    return /^0x[a-fA-F0-9]*$/.test(value);
  },

  isPositiveNumber: (value: string | number): boolean => {
    const num = typeof value === 'string' ? parseFloat(value) : value;
    return !isNaN(num) && num > 0 && isFinite(num);
  },

  isChainId: (value: number): boolean => {
    const validChainIds = [1, 10, 137, 8453, 42161, 11155111, 84532];
    return validChainIds.includes(value);
  },

  sanitizeString: (value: string, maxLength: number = 1000): string => {
    return value
      .replace(/[<>]/g, '') // Remove HTML-like tags
      .slice(0, maxLength)
      .trim();
  },
};

// ═══════════════════════════════════════════════════════════════════════════
// IP Allowlist/Blocklist
// ═══════════════════════════════════════════════════════════════════════════

export class IPFilter {
  private allowlist: Set<string>;
  private blocklist: Set<string>;

  constructor(allowlist: string[] = [], blocklist: string[] = []) {
    this.allowlist = new Set(allowlist);
    this.blocklist = new Set(blocklist);
  }

  isAllowed(ip: string): boolean {
    // If allowlist is not empty, IP must be in it
    if (this.allowlist.size > 0 && !this.allowlist.has(ip)) {
      return false;
    }

    // Check blocklist
    return !this.blocklist.has(ip);
  }

  addToAllowlist(ip: string): void {
    this.allowlist.add(ip);
  }

  addToBlocklist(ip: string): void {
    this.blocklist.add(ip);
  }

  removeFromAllowlist(ip: string): void {
    this.allowlist.delete(ip);
  }

  removeFromBlocklist(ip: string): void {
    this.blocklist.delete(ip);
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default {
  RateLimiter,
  CSRFProtection,
  getSecurityHeaders,
  validators,
  IPFilter,
};
