/**
 * @file wallet.ts
 * @description Secure wallet management utilities
 * @auto-generated by todo-automation
 */

import { createCipheriv, createDecipheriv, randomBytes, scrypt } from 'crypto';
import { promisify } from 'util';
import { privateKeyToAccount } from 'viem/accounts';
import type { Address } from 'viem';

const scryptAsync = promisify(scrypt);

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface EncryptedKeystore {
  version: number;
  address: Address;
  crypto: {
    cipher: string;
    ciphertext: string;
    cipherparams: { iv: string };
    kdf: string;
    kdfparams: {
      n: number;
      r: number;
      p: number;
      dklen: number;
      salt: string;
    };
    mac: string;
  };
}

export interface WalletInfo {
  address: Address;
  createdAt: number;
  label?: string;
  tags?: string[];
}

// ═══════════════════════════════════════════════════════════════════════════
// Key Encryption
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Encrypt a private key with a password
 */
export async function encryptPrivateKey(
  privateKey: `0x${string}`,
  password: string
): Promise<EncryptedKeystore> {
  // Derive key from password using scrypt
  const salt = randomBytes(32);
  const kdfparams = {
    n: 131072, // CPU/memory cost
    r: 8,      // Block size
    p: 1,      // Parallelization
    dklen: 32, // Derived key length
    salt: salt.toString('hex'),
  };

  const derivedKey = (await scryptAsync(
    Buffer.from(password),
    salt,
    kdfparams.dklen,
    { N: kdfparams.n, r: kdfparams.r, p: kdfparams.p }
  )) as Buffer;

  // Encrypt with AES-256-CTR
  const iv = randomBytes(16);
  const cipher = createCipheriv('aes-256-ctr', derivedKey.slice(0, 32), iv);
  
  const privateKeyBuffer = Buffer.from(privateKey.slice(2), 'hex');
  const ciphertext = Buffer.concat([
    cipher.update(privateKeyBuffer),
    cipher.final(),
  ]);

  // Generate MAC for integrity
  const { createHash } = await import('crypto');
  const mac = createHash('sha256')
    .update(Buffer.concat([derivedKey.slice(16, 32), ciphertext]))
    .digest('hex');

  // Get address from private key
  const account = privateKeyToAccount(privateKey);

  return {
    version: 3,
    address: account.address,
    crypto: {
      cipher: 'aes-256-ctr',
      ciphertext: ciphertext.toString('hex'),
      cipherparams: { iv: iv.toString('hex') },
      kdf: 'scrypt',
      kdfparams,
      mac,
    },
  };
}

/**
 * Decrypt a keystore to get the private key
 */
export async function decryptKeystore(
  keystore: EncryptedKeystore,
  password: string
): Promise<`0x${string}`> {
  const { crypto } = keystore;
  const salt = Buffer.from(crypto.kdfparams.salt, 'hex');

  // Derive key from password
  const derivedKey = (await scryptAsync(
    Buffer.from(password),
    salt,
    crypto.kdfparams.dklen,
    {
      N: crypto.kdfparams.n,
      r: crypto.kdfparams.r,
      p: crypto.kdfparams.p,
    }
  )) as Buffer;

  // Verify MAC
  const { createHash } = await import('crypto');
  const ciphertext = Buffer.from(crypto.ciphertext, 'hex');
  const expectedMac = createHash('sha256')
    .update(Buffer.concat([derivedKey.slice(16, 32), ciphertext]))
    .digest('hex');

  if (expectedMac !== crypto.mac) {
    throw new Error('Invalid password or corrupted keystore');
  }

  // Decrypt
  const iv = Buffer.from(crypto.cipherparams.iv, 'hex');
  const decipher = createDecipheriv('aes-256-ctr', derivedKey.slice(0, 32), iv);
  
  const privateKeyBuffer = Buffer.concat([
    decipher.update(ciphertext),
    decipher.final(),
  ]);

  return `0x${privateKeyBuffer.toString('hex')}`;
}

// ═══════════════════════════════════════════════════════════════════════════
// Secure Key Generation
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Generate a new random private key
 */
export function generatePrivateKey(): `0x${string}` {
  const key = randomBytes(32);
  return `0x${key.toString('hex')}`;
}

/**
 * Generate a new wallet with encryption
 */
export async function generateSecureWallet(password: string): Promise<{
  address: Address;
  keystore: EncryptedKeystore;
}> {
  const privateKey = generatePrivateKey();
  const keystore = await encryptPrivateKey(privateKey, password);
  
  return {
    address: keystore.address,
    keystore,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Key Derivation (BIP-44 style)
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Derive multiple addresses from a master key
 */
export function deriveAddresses(
  masterPrivateKey: `0x${string}`,
  count: number
): Array<{ index: number; address: Address; privateKey: `0x${string}` }> {
  const results: Array<{ index: number; address: Address; privateKey: `0x${string}` }> = [];
  
  for (let i = 0; i < count; i++) {
    // Simple derivation (in production, use proper HD wallet derivation)
    const { createHash } = require('crypto');
    const derived = createHash('sha256')
      .update(`${masterPrivateKey}:${i}`)
      .digest('hex');
    
    const privateKey = `0x${derived}` as `0x${string}`;
    const account = privateKeyToAccount(privateKey);
    
    results.push({
      index: i,
      address: account.address,
      privateKey,
    });
  }

  return results;
}

// ═══════════════════════════════════════════════════════════════════════════
// Address Validation
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Validate an Ethereum address with checksum
 */
export function validateAddress(address: string): {
  valid: boolean;
  checksumValid: boolean;
  normalized: Address | null;
} {
  // Basic format check
  if (!/^0x[a-fA-F0-9]{40}$/.test(address)) {
    return { valid: false, checksumValid: false, normalized: null };
  }

  // Checksum validation (EIP-55)
  const { createHash } = require('crypto');
  const addressLower = address.slice(2).toLowerCase();
  const hash = createHash('keccak256').update(addressLower).digest('hex');

  let checksumAddress = '0x';
  for (let i = 0; i < 40; i++) {
    if (parseInt(hash[i], 16) >= 8) {
      checksumAddress += addressLower[i].toUpperCase();
    } else {
      checksumAddress += addressLower[i];
    }
  }

  const checksumValid = address === checksumAddress || address.toLowerCase() === addressLower;

  return {
    valid: true,
    checksumValid,
    normalized: checksumAddress as Address,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default {
  encryptPrivateKey,
  decryptKeystore,
  generatePrivateKey,
  generateSecureWallet,
  deriveAddresses,
  validateAddress,
};
