# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use latest stable Python, ignoring requires-python constraint
FROM python:3.12-slim

WORKDIR /app

# Copy project metadata and lock file
COPY pyproject.toml uv.lock ./

# Install dependencies, bypass Python version requirement
RUN pip install --no-cache-dir . --ignore-requires-python

# Copy application source
COPY . .

# Default command to run the MCP server
CMD ["python", "main.py"]
