apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: crypto-mcp
  app.kubernetes.io/managed-by: kustomize

