# pnpm-workspace.yaml | nich | 14938

packages:
  - "facilitators/*"
  - "facilitators/external-proxies/*"
  - "facilitators/external-proxies/local/*"
  - "servers/*"
  - "clients/*"
  - "clients/external/*"
  - "legacy/servers/*"
  - "legacy/clients/*"
  - "../typescript/packages/*"
  - "../typescript/packages/http/*"
  - "../typescript/packages/mechanisms/*"
  - "../typescript/packages/legacy/*"


# EOF - nirholas | 0x4E494348