/**
 * Completions Command - Generate shell auto-completion scripts
 * Supports bash, zsh, fish, and powershell
 */

import chalk from "chalk";
import fs from "fs-extra";
import path from "path";

interface CompletionsOptions {
  shell?: "bash" | "zsh" | "fish" | "powershell";
  output?: string;
}

export async function completionsCommand(options: CompletionsOptions): Promise<void> {
  console.log(chalk.cyan(`
╔═══════════════════════════════════════════════════════════════╗
║   🐚 x402 Shell Completions                                   ║
╚═══════════════════════════════════════════════════════════════╝
  `));

  const shell = options.shell || detectShell();
  
  if (!shell) {
    console.log(chalk.yellow("Could not detect shell. Please specify with --shell"));
    console.log(chalk.dim("\nSupported shells: bash, zsh, fish, powershell"));
    console.log(chalk.dim("\nExample: x402-deploy completions --shell zsh\n"));
    return;
  }

  console.log(chalk.dim(`Generating completions for ${shell}...\n`));

  let script: string;
  let filename: string;
  let instructions: string;

  switch (shell) {
    case "bash":
      script = generateBashCompletions();
      filename = "x402-deploy.bash";
      instructions = `
To enable completions, add this to your ~/.bashrc:

  ${chalk.cyan("source " + (options.output || "~/.x402-deploy.bash"))}

Or copy to your completions directory:

  ${chalk.cyan("sudo cp " + filename + " /etc/bash_completion.d/x402-deploy")}
`;
      break;

    case "zsh":
      script = generateZshCompletions();
      filename = "_x402-deploy";
      instructions = `
To enable completions, add this to your ~/.zshrc:

  ${chalk.cyan('fpath=(~/.zsh/completions $fpath)')}
  ${chalk.cyan('autoload -U compinit && compinit')}

Then copy the file:

  ${chalk.cyan("mkdir -p ~/.zsh/completions")}
  ${chalk.cyan("cp " + filename + " ~/.zsh/completions/_x402-deploy")}
`;
      break;

    case "fish":
      script = generateFishCompletions();
      filename = "x402-deploy.fish";
      instructions = `
To enable completions, copy to your fish completions directory:

  ${chalk.cyan("mkdir -p ~/.config/fish/completions")}
  ${chalk.cyan("cp " + filename + " ~/.config/fish/completions/x402-deploy.fish")}
`;
      break;

    case "powershell":
      script = generatePowerShellCompletions();
      filename = "x402-deploy.ps1";
      instructions = `
To enable completions, add this to your PowerShell profile:

  ${chalk.cyan(". " + (options.output || "$HOME\\x402-deploy.ps1"))}

Or add to your $PROFILE:

  ${chalk.cyan("Add-Content $PROFILE \". $HOME\\x402-deploy.ps1\"")}
`;
      break;

    default:
      console.log(chalk.red(`Unsupported shell: ${shell}`));
      return;
  }

  // Write to file
  const outputPath = options.output || path.join(process.cwd(), filename);
  await fs.writeFile(outputPath, script);

  console.log(chalk.green(`✅ Completions written to: ${outputPath}\n`));
  console.log(chalk.bold("Installation Instructions:"));
  console.log(instructions);
}

function detectShell(): string | null {
  const shellEnv = process.env.SHELL || "";
  
  if (shellEnv.includes("zsh")) return "zsh";
  if (shellEnv.includes("bash")) return "bash";
  if (shellEnv.includes("fish")) return "fish";
  if (process.platform === "win32") return "powershell";
  
  return null;
}

function generateBashCompletions(): string {
  return `# x402-deploy bash completions
# Generated by x402-deploy completions

_x402_deploy() {
    local cur prev opts commands
    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    commands="init deploy test pricing dashboard status logs upgrade withdraw analytics simulate doctor export import compare marketplace completions"

    # Top-level commands
    if [[ \${COMP_CWORD} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "\${commands}" -- \${cur}) )
        return 0
    fi

    # Command-specific options
    case "\${COMP_WORDS[1]}" in
        init)
            opts="--yes --wallet --network --template -y"
            ;;
        deploy)
            opts="--provider --dry-run --no-discovery --env -p"
            ;;
        test)
            opts="--port"
            ;;
        pricing)
            opts="--route --price --list --remove --interactive -i"
            ;;
        dashboard)
            opts="--json --period --compact --trends"
            ;;
        status)
            opts=""
            ;;
        logs)
            opts="--follow --lines -f -n"
            ;;
        upgrade)
            opts=""
            ;;
        withdraw)
            opts=""
            ;;
        analytics)
            opts="--period --route --export --top -p -r -e -t"
            ;;
        simulate)
            opts="--route --calls --payers -r -c -p"
            ;;
        doctor)
            opts="--fix --verbose -f -v"
            ;;
        export)
            opts="--format --output --include -f -o -i"
            ;;
        import)
            opts="--source --force --merge -s -m"
            ;;
        compare)
            opts="--configs --output -c -o"
            ;;
        marketplace)
            opts="list view search publish categories review"
            ;;
        completions)
            opts="--shell --output"
            ;;
    esac

    COMPREPLY=( $(compgen -W "\${opts}" -- \${cur}) )
    return 0
}

complete -F _x402_deploy x402-deploy
complete -F _x402_deploy x402
`;
}

function generateZshCompletions(): string {
  return `#compdef x402-deploy x402

# x402-deploy zsh completions
# Generated by x402-deploy completions

_x402_deploy() {
    local -a commands
    local -a options

    commands=(
        'init:Initialize x402 in your project'
        'deploy:Deploy with payments enabled'
        'test:Test monetization locally'
        'pricing:Configure pricing'
        'dashboard:View earnings dashboard'
        'status:Check deployment health'
        'logs:View deployment logs'
        'upgrade:Upgrade x402 configuration'
        'withdraw:Withdraw earnings'
        'analytics:Deep analytics and insights'
        'simulate:Simulate payment flows'
        'doctor:Diagnose and fix issues'
        'export:Export configuration'
        'import:Import configuration'
        'compare:Compare configurations'
        'marketplace:Browse API marketplace'
        'completions:Generate shell completions'
    )

    _arguments -C \\
        '1: :->command' \\
        '*: :->args'

    case $state in
        command)
            _describe -t commands 'x402-deploy commands' commands
            ;;
        args)
            case $words[2] in
                init)
                    _arguments \\
                        '-y[Skip prompts and use defaults]' \\
                        '--yes[Skip prompts and use defaults]' \\
                        '--wallet[Wallet address]:address:' \\
                        '--network[Blockchain network]:network:' \\
                        '--template[Use a template]:template:'
                    ;;
                deploy)
                    _arguments \\
                        '-p[Deployment provider]:provider:(railway fly vercel docker)' \\
                        '--provider[Deployment provider]:provider:(railway fly vercel docker)' \\
                        '--dry-run[Show deployment plan]' \\
                        '--no-discovery[Skip x402scan registration]' \\
                        '--env[Environment name]:env:(development staging production)'
                    ;;
                pricing)
                    _arguments \\
                        '--route[Route pattern]:route:' \\
                        '--price[Price]:price:' \\
                        '--list[List current pricing]' \\
                        '--remove[Remove pricing for route]:route:' \\
                        '-i[Interactive pricing editor]' \\
                        '--interactive[Interactive pricing editor]'
                    ;;
                analytics)
                    _arguments \\
                        '-p[Time period]:period:(day week month all)' \\
                        '--period[Time period]:period:(day week month all)' \\
                        '-r[Filter by route]:route:' \\
                        '--route[Filter by route]:route:' \\
                        '-e[Export format]:format:(json csv)' \\
                        '--export[Export format]:format:(json csv)'
                    ;;
                doctor)
                    _arguments \\
                        '-f[Automatically apply fixes]' \\
                        '--fix[Automatically apply fixes]' \\
                        '-v[Show detailed output]' \\
                        '--verbose[Show detailed output]'
                    ;;
                export)
                    _arguments \\
                        '-f[Format]:format:(json yaml env docker)' \\
                        '--format[Format]:format:(json yaml env docker)' \\
                        '-o[Output path]:file:_files' \\
                        '--output[Output path]:file:_files'
                    ;;
                import)
                    _arguments \\
                        '-s[Source file or URL]:source:_files' \\
                        '--source[Source file or URL]:source:_files' \\
                        '--force[Overwrite existing config]' \\
                        '-m[Merge with existing config]' \\
                        '--merge[Merge with existing config]'
                    ;;
                marketplace)
                    local -a subcommands
                    subcommands=(
                        'list:List APIs in marketplace'
                        'view:View API details'
                        'search:Search for APIs'
                        'publish:Publish your API'
                        'categories:List categories'
                        'review:Submit a review'
                    )
                    _describe -t subcommands 'marketplace subcommands' subcommands
                    ;;
            esac
            ;;
    esac
}

_x402_deploy "$@"
`;
}

function generateFishCompletions(): string {
  return `# x402-deploy fish completions
# Generated by x402-deploy completions

# Main commands
complete -c x402-deploy -n "__fish_use_subcommand" -a init -d "Initialize x402 in your project"
complete -c x402-deploy -n "__fish_use_subcommand" -a deploy -d "Deploy with payments enabled"
complete -c x402-deploy -n "__fish_use_subcommand" -a test -d "Test monetization locally"
complete -c x402-deploy -n "__fish_use_subcommand" -a pricing -d "Configure pricing"
complete -c x402-deploy -n "__fish_use_subcommand" -a dashboard -d "View earnings dashboard"
complete -c x402-deploy -n "__fish_use_subcommand" -a status -d "Check deployment health"
complete -c x402-deploy -n "__fish_use_subcommand" -a logs -d "View deployment logs"
complete -c x402-deploy -n "__fish_use_subcommand" -a upgrade -d "Upgrade x402 configuration"
complete -c x402-deploy -n "__fish_use_subcommand" -a withdraw -d "Withdraw earnings"
complete -c x402-deploy -n "__fish_use_subcommand" -a analytics -d "Deep analytics and insights"
complete -c x402-deploy -n "__fish_use_subcommand" -a simulate -d "Simulate payment flows"
complete -c x402-deploy -n "__fish_use_subcommand" -a doctor -d "Diagnose and fix issues"
complete -c x402-deploy -n "__fish_use_subcommand" -a export -d "Export configuration"
complete -c x402-deploy -n "__fish_use_subcommand" -a import -d "Import configuration"
complete -c x402-deploy -n "__fish_use_subcommand" -a compare -d "Compare configurations"
complete -c x402-deploy -n "__fish_use_subcommand" -a marketplace -d "Browse API marketplace"
complete -c x402-deploy -n "__fish_use_subcommand" -a completions -d "Generate shell completions"

# init options
complete -c x402-deploy -n "__fish_seen_subcommand_from init" -s y -l yes -d "Skip prompts"
complete -c x402-deploy -n "__fish_seen_subcommand_from init" -l wallet -d "Wallet address"
complete -c x402-deploy -n "__fish_seen_subcommand_from init" -l network -d "Blockchain network"
complete -c x402-deploy -n "__fish_seen_subcommand_from init" -l template -d "Use a template"

# deploy options
complete -c x402-deploy -n "__fish_seen_subcommand_from deploy" -s p -l provider -d "Provider" -a "railway fly vercel docker"
complete -c x402-deploy -n "__fish_seen_subcommand_from deploy" -l dry-run -d "Show deployment plan"
complete -c x402-deploy -n "__fish_seen_subcommand_from deploy" -l no-discovery -d "Skip registration"
complete -c x402-deploy -n "__fish_seen_subcommand_from deploy" -l env -d "Environment" -a "development staging production"

# pricing options
complete -c x402-deploy -n "__fish_seen_subcommand_from pricing" -l route -d "Route pattern"
complete -c x402-deploy -n "__fish_seen_subcommand_from pricing" -l price -d "Price"
complete -c x402-deploy -n "__fish_seen_subcommand_from pricing" -l list -d "List pricing"
complete -c x402-deploy -n "__fish_seen_subcommand_from pricing" -l remove -d "Remove route"
complete -c x402-deploy -n "__fish_seen_subcommand_from pricing" -s i -l interactive -d "Interactive editor"

# analytics options
complete -c x402-deploy -n "__fish_seen_subcommand_from analytics" -s p -l period -d "Time period" -a "day week month all"
complete -c x402-deploy -n "__fish_seen_subcommand_from analytics" -s e -l export -d "Export format" -a "json csv"

# doctor options
complete -c x402-deploy -n "__fish_seen_subcommand_from doctor" -s f -l fix -d "Auto-fix issues"
complete -c x402-deploy -n "__fish_seen_subcommand_from doctor" -s v -l verbose -d "Verbose output"

# export options
complete -c x402-deploy -n "__fish_seen_subcommand_from export" -s f -l format -d "Format" -a "json yaml env docker"
complete -c x402-deploy -n "__fish_seen_subcommand_from export" -s o -l output -d "Output path"

# import options
complete -c x402-deploy -n "__fish_seen_subcommand_from import" -s s -l source -d "Source file"
complete -c x402-deploy -n "__fish_seen_subcommand_from import" -l force -d "Force overwrite"
complete -c x402-deploy -n "__fish_seen_subcommand_from import" -s m -l merge -d "Merge configs"

# completions options
complete -c x402-deploy -n "__fish_seen_subcommand_from completions" -l shell -d "Shell type" -a "bash zsh fish powershell"
complete -c x402-deploy -n "__fish_seen_subcommand_from completions" -l output -d "Output file"

# marketplace subcommands
complete -c x402-deploy -n "__fish_seen_subcommand_from marketplace" -a list -d "List APIs"
complete -c x402-deploy -n "__fish_seen_subcommand_from marketplace" -a view -d "View API details"
complete -c x402-deploy -n "__fish_seen_subcommand_from marketplace" -a search -d "Search APIs"
complete -c x402-deploy -n "__fish_seen_subcommand_from marketplace" -a publish -d "Publish API"
complete -c x402-deploy -n "__fish_seen_subcommand_from marketplace" -a categories -d "List categories"
complete -c x402-deploy -n "__fish_seen_subcommand_from marketplace" -a review -d "Submit review"
`;
}

function generatePowerShellCompletions(): string {
  return `# x402-deploy PowerShell completions
# Generated by x402-deploy completions

$script:x402Commands = @(
    'init'
    'deploy'
    'test'
    'pricing'
    'dashboard'
    'status'
    'logs'
    'upgrade'
    'withdraw'
    'analytics'
    'simulate'
    'doctor'
    'export'
    'import'
    'compare'
    'marketplace'
    'completions'
)

$script:x402CommandOptions = @{
    'init' = @('-y', '--yes', '--wallet', '--network', '--template')
    'deploy' = @('-p', '--provider', '--dry-run', '--no-discovery', '--env')
    'test' = @('--port')
    'pricing' = @('--route', '--price', '--list', '--remove', '-i', '--interactive')
    'dashboard' = @('--json', '--period', '--compact', '--trends')
    'status' = @()
    'logs' = @('-f', '--follow', '-n', '--lines')
    'upgrade' = @()
    'withdraw' = @()
    'analytics' = @('-p', '--period', '-r', '--route', '-e', '--export', '-t', '--top')
    'simulate' = @('-r', '--route', '-c', '--calls', '-p', '--payers')
    'doctor' = @('-f', '--fix', '-v', '--verbose')
    'export' = @('-f', '--format', '-o', '--output', '-i', '--include')
    'import' = @('-s', '--source', '--force', '-m', '--merge')
    'compare' = @('-c', '--configs', '-o', '--output')
    'marketplace' = @('list', 'view', 'search', 'publish', 'categories', 'review')
    'completions' = @('--shell', '--output')
}

Register-ArgumentCompleter -Native -CommandName x402-deploy, x402 -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $command = $commandAst.CommandElements[0].Value
    $words = $commandAst.CommandElements | ForEach-Object { $_.Extent.Text }
    
    if ($words.Count -eq 1) {
        # Complete commands
        $script:x402Commands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
    }
    elseif ($words.Count -ge 2) {
        # Complete options for command
        $cmd = $words[1]
        $options = $script:x402CommandOptions[$cmd]
        
        if ($options) {
            $options | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
            }
        }
    }
}

Write-Host "x402-deploy completions loaded" -ForegroundColor Cyan
`;
}
