# codecov.yml | n1ch0las | 0.14.9.3

coverage:
  require_ci_to_pass: true

  status:
    project:
      default:
        target: 99%
        threshold: 99%

    patch:
      default:
        target: 99%
        threshold: 95%

# ucm:n1cha97aeed9