/**
 * @file error-handling.ts
 * @description Centralized error handling utilities
 * @auto-generated by todo-automation
 */

// ═══════════════════════════════════════════════════════════════════════════
// Error Types
// ═══════════════════════════════════════════════════════════════════════════

export class AppError extends Error {
  public readonly code: string;
  public readonly statusCode: number;
  public readonly isOperational: boolean;
  public readonly context?: Record<string, unknown>;

  constructor(
    message: string,
    options?: {
      code?: string;
      statusCode?: number;
      isOperational?: boolean;
      context?: Record<string, unknown>;
      cause?: Error;
    }
  ) {
    super(message, { cause: options?.cause });
    this.name = 'AppError';
    this.code = options?.code || 'UNKNOWN_ERROR';
    this.statusCode = options?.statusCode || 500;
    this.isOperational = options?.isOperational ?? true;
    this.context = options?.context;
    Error.captureStackTrace(this, this.constructor);
  }
}

export class ValidationError extends AppError {
  constructor(message: string, context?: Record<string, unknown>) {
    super(message, {
      code: 'VALIDATION_ERROR',
      statusCode: 400,
      isOperational: true,
      context,
    });
    this.name = 'ValidationError';
  }
}

export class NotFoundError extends AppError {
  constructor(resource: string, identifier?: string) {
    super(`${resource} not found${identifier ? `: ${identifier}` : ''}`, {
      code: 'NOT_FOUND',
      statusCode: 404,
      isOperational: true,
      context: { resource, identifier },
    });
    this.name = 'NotFoundError';
  }
}

export class AuthenticationError extends AppError {
  constructor(message: string = 'Authentication required') {
    super(message, {
      code: 'UNAUTHENTICATED',
      statusCode: 401,
      isOperational: true,
    });
    this.name = 'AuthenticationError';
  }
}

export class AuthorizationError extends AppError {
  constructor(message: string = 'Permission denied') {
    super(message, {
      code: 'UNAUTHORIZED',
      statusCode: 403,
      isOperational: true,
    });
    this.name = 'AuthorizationError';
  }
}

export class RateLimitError extends AppError {
  constructor(retryAfter?: number) {
    super('Rate limit exceeded', {
      code: 'RATE_LIMITED',
      statusCode: 429,
      isOperational: true,
      context: { retryAfter },
    });
    this.name = 'RateLimitError';
  }
}

export class ChainError extends AppError {
  constructor(message: string, chainId: number, cause?: Error) {
    super(message, {
      code: 'CHAIN_ERROR',
      statusCode: 502,
      isOperational: true,
      context: { chainId },
      cause,
    });
    this.name = 'ChainError';
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Error Handling Utilities
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Safely extract error message from unknown error
 */
export function getErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  if (typeof error === 'string') {
    return error;
  }
  if (error && typeof error === 'object' && 'message' in error) {
    return String((error as { message: unknown }).message);
  }
  return 'An unknown error occurred';
}

/**
 * Safely extract error code from unknown error
 */
export function getErrorCode(error: unknown): string {
  if (error instanceof AppError) {
    return error.code;
  }
  if (error && typeof error === 'object' && 'code' in error) {
    return String((error as { code: unknown }).code);
  }
  return 'UNKNOWN_ERROR';
}

/**
 * Wrap async function with error handling
 */
export function catchAsync<T extends (...args: unknown[]) => Promise<unknown>>(
  fn: T,
  errorHandler?: (error: unknown) => void
): T {
  return (async (...args: Parameters<T>) => {
    try {
      return await fn(...args);
    } catch (error) {
      if (errorHandler) {
        errorHandler(error);
      } else {
        console.error('[catchAsync]', getErrorMessage(error));
      }
      throw error;
    }
  }) as T;
}

/**
 * Try-catch wrapper that returns Result type
 */
export type Result<T, E = Error> =
  | { success: true; data: T }
  | { success: false; error: E };

export async function tryCatch<T>(
  fn: () => Promise<T>
): Promise<Result<T, Error>> {
  try {
    const data = await fn();
    return { success: true, data };
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error : new Error(getErrorMessage(error)),
    };
  }
}

/**
 * Retry a function with exponential backoff
 */
export async function retry<T>(
  fn: () => Promise<T>,
  options?: {
    maxAttempts?: number;
    initialDelayMs?: number;
    maxDelayMs?: number;
    backoffMultiplier?: number;
    shouldRetry?: (error: unknown) => boolean;
  }
): Promise<T> {
  const {
    maxAttempts = 3,
    initialDelayMs = 1000,
    maxDelayMs = 30000,
    backoffMultiplier = 2,
    shouldRetry = () => true,
  } = options || {};

  let lastError: unknown;
  let delay = initialDelayMs;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      return await fn();
    } catch (error) {
      lastError = error;

      if (attempt === maxAttempts || !shouldRetry(error)) {
        break;
      }

      console.warn(
        `[retry] Attempt ${attempt}/${maxAttempts} failed: ${getErrorMessage(error)}. ` +
          `Retrying in ${delay}ms...`
      );

      await new Promise((resolve) => setTimeout(resolve, delay));
      delay = Math.min(delay * backoffMultiplier, maxDelayMs);
    }
  }

  throw lastError;
}

// ═══════════════════════════════════════════════════════════════════════════
// Logging
// ═══════════════════════════════════════════════════════════════════════════

export interface ErrorLog {
  timestamp: string;
  level: 'error' | 'warn' | 'info';
  message: string;
  code?: string;
  stack?: string;
  context?: Record<string, unknown>;
}

/**
 * Create structured error log
 */
export function createErrorLog(error: unknown, context?: Record<string, unknown>): ErrorLog {
  const message = getErrorMessage(error);
  const code = getErrorCode(error);
  const stack = error instanceof Error ? error.stack : undefined;

  return {
    timestamp: new Date().toISOString(),
    level: 'error',
    message,
    code,
    stack,
    context: {
      ...context,
      ...(error instanceof AppError ? error.context : {}),
    },
  };
}

/**
 * Log error with structured format
 */
export function logError(error: unknown, context?: Record<string, unknown>): void {
  const log = createErrorLog(error, context);
  console.error(JSON.stringify(log, null, 2));
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default {
  AppError,
  ValidationError,
  NotFoundError,
  AuthenticationError,
  AuthorizationError,
  RateLimitError,
  ChainError,
  getErrorMessage,
  getErrorCode,
  catchAsync,
  tryCatch,
  retry,
  createErrorLog,
  logError,
};
