/**
 * @file logger.ts
 * @description Structured logging utility for production use
 * @auto-generated by todo-automation
 */

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'fatal';

export interface LogEntry {
  timestamp: string;
  level: LogLevel;
  message: string;
  service?: string;
  context?: Record<string, unknown>;
  error?: {
    name: string;
    message: string;
    stack?: string;
  };
}

export interface LoggerConfig {
  level: LogLevel;
  service: string;
  pretty?: boolean;
  enabled?: boolean;
}

// ═══════════════════════════════════════════════════════════════════════════
// Log Level Priority
// ═══════════════════════════════════════════════════════════════════════════

const LOG_LEVELS: Record<LogLevel, number> = {
  debug: 0,
  info: 1,
  warn: 2,
  error: 3,
  fatal: 4,
};

// ═══════════════════════════════════════════════════════════════════════════
// Logger Class
// ═══════════════════════════════════════════════════════════════════════════

export class Logger {
  private config: Required<LoggerConfig>;

  constructor(config: LoggerConfig) {
    this.config = {
      level: config.level || 'info',
      service: config.service || 'app',
      pretty: config.pretty ?? process.env.NODE_ENV !== 'production',
      enabled: config.enabled ?? true,
    };
  }

  private shouldLog(level: LogLevel): boolean {
    if (!this.config.enabled) return false;
    return LOG_LEVELS[level] >= LOG_LEVELS[this.config.level];
  }

  private formatEntry(entry: LogEntry): string {
    if (this.config.pretty) {
      const levelColors: Record<LogLevel, string> = {
        debug: '\x1b[36m', // Cyan
        info: '\x1b[32m',  // Green
        warn: '\x1b[33m',  // Yellow
        error: '\x1b[31m', // Red
        fatal: '\x1b[35m', // Magenta
      };
      const reset = '\x1b[0m';
      const color = levelColors[entry.level];
      
      let output = `${color}[${entry.level.toUpperCase()}]${reset} ${entry.message}`;
      
      if (entry.context && Object.keys(entry.context).length > 0) {
        output += ` ${JSON.stringify(entry.context)}`;
      }
      
      if (entry.error) {
        output += `\n  Error: ${entry.error.message}`;
        if (entry.error.stack) {
          output += `\n  ${entry.error.stack.split('\n').slice(1).join('\n  ')}`;
        }
      }
      
      return output;
    }
    
    return JSON.stringify(entry);
  }

  private log(level: LogLevel, message: string, context?: Record<string, unknown>, error?: Error): void {
    if (!this.shouldLog(level)) return;

    const entry: LogEntry = {
      timestamp: new Date().toISOString(),
      level,
      message,
      service: this.config.service,
      context,
    };

    if (error) {
      entry.error = {
        name: error.name,
        message: error.message,
        stack: error.stack,
      };
    }

    const output = this.formatEntry(entry);

    switch (level) {
      case 'debug':
      case 'info':
        console.log(output);
        break;
      case 'warn':
        console.warn(output);
        break;
      case 'error':
      case 'fatal':
        console.error(output);
        break;
    }
  }

  debug(message: string, context?: Record<string, unknown>): void {
    this.log('debug', message, context);
  }

  info(message: string, context?: Record<string, unknown>): void {
    this.log('info', message, context);
  }

  warn(message: string, context?: Record<string, unknown>): void {
    this.log('warn', message, context);
  }

  error(message: string, error?: Error | unknown, context?: Record<string, unknown>): void {
    const err = error instanceof Error ? error : undefined;
    const ctx = error instanceof Error ? context : (error as Record<string, unknown>);
    this.log('error', message, ctx, err);
  }

  fatal(message: string, error?: Error, context?: Record<string, unknown>): void {
    this.log('fatal', message, context, error);
  }

  child(context: Record<string, unknown>): Logger {
    const child = new Logger(this.config);
    const originalLog = child.log.bind(child);
    child.log = (level, message, ctx, error) => {
      originalLog(level, message, { ...context, ...ctx }, error);
    };
    return child;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Default Logger Instance
// ═══════════════════════════════════════════════════════════════════════════

export const logger = new Logger({
  level: (process.env.LOG_LEVEL as LogLevel) || 'info',
  service: process.env.SERVICE_NAME || 'universal-crypto-mcp',
  pretty: process.env.NODE_ENV !== 'production',
});

// ═══════════════════════════════════════════════════════════════════════════
// Convenience Functions
// ═══════════════════════════════════════════════════════════════════════════

export function createLogger(service: string, level?: LogLevel): Logger {
  return new Logger({
    level: level || (process.env.LOG_LEVEL as LogLevel) || 'info',
    service,
    pretty: process.env.NODE_ENV !== 'production',
  });
}

// ═══════════════════════════════════════════════════════════════════════════
// Request Logging Middleware
// ═══════════════════════════════════════════════════════════════════════════

export interface RequestLog {
  method: string;
  path: string;
  statusCode: number;
  durationMs: number;
  userAgent?: string;
  ip?: string;
}

export function logRequest(log: RequestLog): void {
  const level: LogLevel = log.statusCode >= 500 ? 'error' : log.statusCode >= 400 ? 'warn' : 'info';
  logger[level](`${log.method} ${log.path} ${log.statusCode} ${log.durationMs}ms`, {
    ...log,
  });
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default logger;
