/**
 * @file init.ts
 * @description Database initialization and migration system
 * @implements cli.ts#L56 TODO: Implement database initialization
 * @implements cli.ts#L76 TODO: Implement migrations
 * @auto-generated by todo-automation
 */

import { drizzle } from 'drizzle-orm/postgres-js';
import { migrate } from 'drizzle-orm/postgres-js/migrator';
import postgres from 'postgres';
import * as schema from './schema';
import { sql } from 'drizzle-orm';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface DatabaseConfig {
  connectionString: string;
  maxConnections?: number;
  idleTimeout?: number;
  ssl?: boolean | 'require' | 'allow' | 'prefer';
}

export interface MigrationResult {
  success: boolean;
  appliedMigrations: string[];
  error?: string;
}

export interface HealthCheckResult {
  connected: boolean;
  latencyMs: number;
  version?: string;
  error?: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// Database Manager
// ═══════════════════════════════════════════════════════════════════════════

export class DatabaseManager {
  private client: ReturnType<typeof postgres> | null = null;
  private db: ReturnType<typeof drizzle> | null = null;
  private config: DatabaseConfig;

  constructor(config: DatabaseConfig) {
    this.config = {
      maxConnections: 10,
      idleTimeout: 30,
      ssl: 'prefer',
      ...config,
    };
  }

  /**
   * Initialize database connection
   */
  async initialize(): Promise<void> {
    console.log('[Database] Initializing connection...');
    
    this.client = postgres(this.config.connectionString, {
      max: this.config.maxConnections,
      idle_timeout: this.config.idleTimeout,
      ssl: this.config.ssl,
      onnotice: () => {}, // Suppress notices
    });

    this.db = drizzle(this.client, { schema });

    // Test connection
    const health = await this.healthCheck();
    if (!health.connected) {
      throw new Error(`Database connection failed: ${health.error}`);
    }

    console.log(`[Database] Connected to PostgreSQL ${health.version}`);
  }

  /**
   * Run database migrations
   */
  async runMigrations(migrationsFolder: string = './drizzle'): Promise<MigrationResult> {
    if (!this.db || !this.client) {
      return { success: false, appliedMigrations: [], error: 'Database not initialized' };
    }

    console.log('[Database] Running migrations...');

    try {
      await migrate(this.db, { migrationsFolder });
      
      // Get list of applied migrations
      const result = await this.client`
        SELECT name FROM drizzle.__drizzle_migrations 
        ORDER BY created_at DESC
      `.catch(() => []);

      const appliedMigrations = result.map((r: { name: string }) => r.name);
      
      console.log(`[Database] Applied ${appliedMigrations.length} migrations`);
      
      return { success: true, appliedMigrations };
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Migration failed';
      console.error('[Database] Migration error:', message);
      return { success: false, appliedMigrations: [], error: message };
    }
  }

  /**
   * Create required tables if they don't exist
   */
  async createTables(): Promise<void> {
    if (!this.client) throw new Error('Database not initialized');

    console.log('[Database] Creating tables...');

    // Campaigns table
    await this.client`
      CREATE TABLE IF NOT EXISTS campaigns (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name VARCHAR(255) NOT NULL,
        status VARCHAR(50) DEFAULT 'pending',
        target_volume DECIMAL(20, 8) NOT NULL,
        current_volume DECIMAL(20, 8) DEFAULT 0,
        token_address VARCHAR(66) NOT NULL,
        chain_id INTEGER NOT NULL,
        start_time TIMESTAMP,
        end_time TIMESTAMP,
        config JSONB DEFAULT '{}',
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      )
    `;

    // Trades table
    await this.client`
      CREATE TABLE IF NOT EXISTS trades (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        campaign_id UUID REFERENCES campaigns(id),
        tx_hash VARCHAR(66) UNIQUE NOT NULL,
        direction VARCHAR(10) NOT NULL,
        amount DECIMAL(20, 8) NOT NULL,
        price DECIMAL(20, 8) NOT NULL,
        status VARCHAR(50) DEFAULT 'pending',
        wallet_address VARCHAR(66) NOT NULL,
        gas_used DECIMAL(20, 8),
        error_message TEXT,
        created_at TIMESTAMP DEFAULT NOW()
      )
    `;

    // Wallets table
    await this.client`
      CREATE TABLE IF NOT EXISTS wallets (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        address VARCHAR(66) UNIQUE NOT NULL,
        chain VARCHAR(50) NOT NULL,
        label VARCHAR(255),
        balance JSONB DEFAULT '{}',
        last_used TIMESTAMP,
        created_at TIMESTAMP DEFAULT NOW()
      )
    `;

    // Bots table
    await this.client`
      CREATE TABLE IF NOT EXISTS bots (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        name VARCHAR(255) NOT NULL,
        type VARCHAR(50) NOT NULL,
        status VARCHAR(50) DEFAULT 'stopped',
        config JSONB DEFAULT '{}',
        stats JSONB DEFAULT '{}',
        created_at TIMESTAMP DEFAULT NOW(),
        updated_at TIMESTAMP DEFAULT NOW()
      )
    `;

    // Payments table (for x402)
    await this.client`
      CREATE TABLE IF NOT EXISTS payments (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        tx_hash VARCHAR(66) UNIQUE,
        payer_address VARCHAR(66) NOT NULL,
        recipient_address VARCHAR(66) NOT NULL,
        amount DECIMAL(20, 8) NOT NULL,
        asset_address VARCHAR(66) NOT NULL,
        chain_id INTEGER NOT NULL,
        status VARCHAR(50) DEFAULT 'pending',
        resource VARCHAR(512),
        settled_at TIMESTAMP,
        refunded_at TIMESTAMP,
        created_at TIMESTAMP DEFAULT NOW()
      )
    `;

    // Indexes
    await this.client`
      CREATE INDEX IF NOT EXISTS idx_campaigns_status ON campaigns(status);
      CREATE INDEX IF NOT EXISTS idx_trades_campaign ON trades(campaign_id);
      CREATE INDEX IF NOT EXISTS idx_trades_status ON trades(status);
      CREATE INDEX IF NOT EXISTS idx_payments_payer ON payments(payer_address);
      CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
    `;

    console.log('[Database] Tables created successfully');
  }

  /**
   * Seed initial data
   */
  async seed(): Promise<void> {
    if (!this.client) throw new Error('Database not initialized');

    console.log('[Database] Seeding initial data...');

    // Check if already seeded
    const existingBots = await this.client`SELECT COUNT(*) as count FROM bots`;
    if (existingBots[0].count > 0) {
      console.log('[Database] Database already seeded, skipping...');
      return;
    }

    // Insert default bot configurations
    await this.client`
      INSERT INTO bots (name, type, status, config) VALUES
      ('Volume Bot Alpha', 'volume', 'stopped', '{"maxTradesPerMinute": 10, "minTradeSize": 0.1, "maxTradeSize": 1.0}'),
      ('Market Maker Beta', 'market_maker', 'stopped', '{"spread": 0.002, "orderSize": 0.5, "rebalanceThreshold": 0.05}'),
      ('Arbitrage Scanner', 'arbitrage', 'stopped', '{"minProfitBps": 50, "maxGasPrice": 100, "chains": [1, 8453, 42161]}')
    `;

    console.log('[Database] Seeding complete');
  }

  /**
   * Health check
   */
  async healthCheck(): Promise<HealthCheckResult> {
    if (!this.client) {
      return { connected: false, latencyMs: 0, error: 'Not initialized' };
    }

    const start = Date.now();
    
    try {
      const result = await this.client`SELECT version()`;
      return {
        connected: true,
        latencyMs: Date.now() - start,
        version: result[0]?.version,
      };
    } catch (error) {
      return {
        connected: false,
        latencyMs: Date.now() - start,
        error: error instanceof Error ? error.message : 'Unknown error',
      };
    }
  }

  /**
   * Get database instance
   */
  getDb() {
    if (!this.db) throw new Error('Database not initialized');
    return this.db;
  }

  /**
   * Get raw client
   */
  getClient() {
    if (!this.client) throw new Error('Database not initialized');
    return this.client;
  }

  /**
   * Close connection
   */
  async close(): Promise<void> {
    if (this.client) {
      await this.client.end();
      this.client = null;
      this.db = null;
      console.log('[Database] Connection closed');
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// CLI Database Commands
// ═══════════════════════════════════════════════════════════════════════════

export async function initializeDatabase(connectionString: string): Promise<void> {
  const manager = new DatabaseManager({ connectionString });
  
  try {
    await manager.initialize();
    await manager.createTables();
    await manager.seed();
    console.log('✅ Database initialization complete');
  } finally {
    await manager.close();
  }
}

export async function runDatabaseMigrations(
  connectionString: string,
  migrationsPath: string
): Promise<MigrationResult> {
  const manager = new DatabaseManager({ connectionString });
  
  try {
    await manager.initialize();
    return await manager.runMigrations(migrationsPath);
  } finally {
    await manager.close();
  }
}

export async function checkDatabaseHealth(connectionString: string): Promise<HealthCheckResult> {
  const manager = new DatabaseManager({ connectionString });
  
  try {
    await manager.initialize();
    return await manager.healthCheck();
  } finally {
    await manager.close();
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default DatabaseManager;
