import type {
  MarketplaceService,
  Subscription,
  ServiceReview,
  PlatformStats,
} from './types';

export const mockServices: MarketplaceService[] = [
  {
    id: 'svc_1',
    name: 'GPT-4 Turbo API',
    description: 'Access to OpenAI\'s GPT-4 Turbo model through our optimized API gateway. Perfect for building AI-powered applications with the latest language model capabilities.',
    shortDescription: 'High-performance GPT-4 Turbo API with streaming support',
    category: 'ai-models',
    provider: {
      id: 'prov_1',
      name: 'AI Gateway Pro',
      walletAddress: '0x1234...5678',
      verified: true,
      reputationScore: 95,
      totalServices: 12,
      joinedAt: new Date('2023-06-15'),
    },
    pricing: {
      type: 'pay-per-use',
      payPerUse: { pricePerRequest: 0.002, currency: 'USD' },
    },
    reputation: {
      score: 95,
      rating: 4.8,
      totalReviews: 342,
      verifiedPayments: 15420,
      uptime: 99.95,
      responseTime: 245,
      successRate: 99.2,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
      { id: 'top-rated', name: 'Top Rated', icon: '⭐', color: 'yellow' },
    ],
    tags: ['gpt-4', 'ai', 'nlp', 'chatbot', 'language-model'],
    endpoint: 'https://api.aigateway.pro/v1/gpt4',
    documentationUrl: 'https://docs.aigateway.pro/gpt4',
    status: 'active',
    usageCount: 1250000,
    createdAt: new Date('2023-07-01'),
    updatedAt: new Date('2024-01-15'),
    isOnline: true,
    featured: true,
  },
  {
    id: 'svc_2',
    name: 'Crypto Price Oracle',
    description: 'Real-time cryptocurrency price feeds with sub-second updates. Supports 500+ tokens across major exchanges with VWAP and historical data.',
    shortDescription: 'Real-time crypto price feeds for 500+ tokens',
    category: 'market-data',
    provider: {
      id: 'prov_2',
      name: 'DataFeed Labs',
      walletAddress: '0xabcd...ef01',
      verified: true,
      reputationScore: 92,
      totalServices: 5,
      joinedAt: new Date('2023-04-20'),
    },
    pricing: {
      type: 'subscription',
      subscription: {
        plans: [
          {
            name: 'starter',
            price: 29,
            currency: 'USD',
            billingPeriod: 'monthly',
            requestsIncluded: 10000,
            features: ['100 tokens', 'REST API', 'Email support'],
          },
          {
            name: 'professional',
            price: 99,
            currency: 'USD',
            billingPeriod: 'monthly',
            requestsIncluded: 100000,
            features: ['500+ tokens', 'WebSocket', 'Priority support', 'Historical data'],
          },
        ],
      },
    },
    reputation: {
      score: 92,
      rating: 4.6,
      totalReviews: 189,
      verifiedPayments: 8750,
      uptime: 99.99,
      responseTime: 45,
      successRate: 99.8,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
    ],
    tags: ['crypto', 'prices', 'oracle', 'defi', 'trading'],
    endpoint: 'https://api.datafeedlabs.io/v2/prices',
    status: 'active',
    usageCount: 890000,
    createdAt: new Date('2023-05-15'),
    updatedAt: new Date('2024-01-10'),
    isOnline: true,
    featured: true,
  },
  {
    id: 'svc_3',
    name: 'Sentiment Analysis API',
    description: 'Analyze sentiment from social media, news, and custom text. Multi-language support with crypto-specific training data.',
    shortDescription: 'AI-powered sentiment analysis for crypto & finance',
    category: 'sentiment',
    provider: {
      id: 'prov_3',
      name: 'SentimentAI',
      walletAddress: '0x7890...1234',
      verified: false,
      reputationScore: 78,
      totalServices: 2,
      joinedAt: new Date('2024-01-05'),
    },
    pricing: {
      type: 'pay-per-use',
      payPerUse: { pricePerRequest: 0.0005, currency: 'USD' },
    },
    reputation: {
      score: 78,
      rating: 4.2,
      totalReviews: 45,
      verifiedPayments: 2340,
      uptime: 98.5,
      responseTime: 180,
      successRate: 97.5,
    },
    badges: [
      { id: 'new', name: 'New', icon: '🆕', color: 'blue' },
    ],
    tags: ['sentiment', 'nlp', 'social', 'twitter', 'news'],
    endpoint: 'https://api.sentimentai.co/analyze',
    status: 'active',
    usageCount: 125000,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-20'),
    isOnline: true,
    featured: false,
  },
  {
    id: 'svc_4',
    name: 'Trading Signals Pro',
    description: 'AI-generated trading signals for major crypto pairs. Backtested strategies with 65%+ win rate.',
    shortDescription: 'AI trading signals with proven track record',
    category: 'trading-signals',
    provider: {
      id: 'prov_4',
      name: 'QuantLab',
      walletAddress: '0xdef0...5678',
      verified: true,
      reputationScore: 88,
      totalServices: 3,
      joinedAt: new Date('2023-08-10'),
    },
    pricing: {
      type: 'subscription',
      subscription: {
        plans: [
          {
            name: 'professional',
            price: 199,
            currency: 'USD',
            billingPeriod: 'monthly',
            requestsIncluded: 50000,
            features: ['10 pairs', 'Telegram alerts', 'API access'],
          },
          {
            name: 'enterprise',
            price: 499,
            currency: 'USD',
            billingPeriod: 'monthly',
            requestsIncluded: 500000,
            features: ['All pairs', 'Custom strategies', 'Dedicated support'],
          },
        ],
      },
    },
    reputation: {
      score: 88,
      rating: 4.5,
      totalReviews: 156,
      verifiedPayments: 4520,
      uptime: 99.5,
      responseTime: 120,
      successRate: 98.5,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
      { id: 'top-rated', name: 'Top Rated', icon: '⭐', color: 'yellow' },
    ],
    tags: ['trading', 'signals', 'ai', 'crypto', 'quant'],
    endpoint: 'https://api.quantlab.io/signals',
    status: 'active',
    usageCount: 456000,
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2024-01-18'),
    isOnline: true,
    featured: true,
  },
  {
    id: 'svc_5',
    name: 'Blockchain Analytics',
    description: 'On-chain analytics for Ethereum, Base, and Arbitrum. Track wallet activity, token flows, and smart contract interactions.',
    shortDescription: 'Comprehensive on-chain analytics API',
    category: 'blockchain-data',
    provider: {
      id: 'prov_5',
      name: 'ChainMetrics',
      walletAddress: '0x4567...89ab',
      verified: true,
      reputationScore: 90,
      totalServices: 4,
      joinedAt: new Date('2023-03-15'),
    },
    pricing: {
      type: 'pay-per-use',
      payPerUse: { pricePerRequest: 0.001, currency: 'USD' },
    },
    reputation: {
      score: 90,
      rating: 4.7,
      totalReviews: 234,
      verifiedPayments: 9870,
      uptime: 99.9,
      responseTime: 350,
      successRate: 99.1,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
    ],
    tags: ['blockchain', 'analytics', 'ethereum', 'defi', 'on-chain'],
    endpoint: 'https://api.chainmetrics.io/v1',
    status: 'active',
    usageCount: 678000,
    createdAt: new Date('2023-04-01'),
    updatedAt: new Date('2024-01-12'),
    isOnline: true,
    featured: false,
  },
  {
    id: 'svc_6',
    name: 'Image Generation API',
    description: 'State-of-the-art image generation using Stable Diffusion XL. Create stunning visuals from text prompts.',
    shortDescription: 'SDXL-powered image generation API',
    category: 'computer-vision',
    provider: {
      id: 'prov_6',
      name: 'PixelForge',
      walletAddress: '0xcdef...0123',
      verified: true,
      reputationScore: 85,
      totalServices: 6,
      joinedAt: new Date('2023-09-01'),
    },
    pricing: {
      type: 'pay-per-use',
      payPerUse: { pricePerRequest: 0.02, currency: 'USD' },
    },
    reputation: {
      score: 85,
      rating: 4.4,
      totalReviews: 178,
      verifiedPayments: 6540,
      uptime: 98.8,
      responseTime: 4500,
      successRate: 97.8,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
    ],
    tags: ['image', 'generation', 'ai', 'sdxl', 'creative'],
    endpoint: 'https://api.pixelforge.ai/generate',
    status: 'active',
    usageCount: 234000,
    createdAt: new Date('2023-09-15'),
    updatedAt: new Date('2024-01-08'),
    isOnline: true,
    featured: false,
  },
  {
    id: 'svc_7',
    name: 'Speech-to-Text Pro',
    description: 'High-accuracy speech recognition supporting 50+ languages. Real-time transcription with speaker diarization.',
    shortDescription: 'Multi-language speech recognition API',
    category: 'speech',
    provider: {
      id: 'prov_7',
      name: 'VoiceAI Labs',
      walletAddress: '0x2345...6789',
      verified: true,
      reputationScore: 91,
      totalServices: 3,
      joinedAt: new Date('2023-05-20'),
    },
    pricing: {
      type: 'subscription',
      subscription: {
        plans: [
          {
            name: 'starter',
            price: 49,
            currency: 'USD',
            billingPeriod: 'monthly',
            requestsIncluded: 5000,
            features: ['10 languages', 'REST API', 'Standard quality'],
          },
          {
            name: 'professional',
            price: 149,
            currency: 'USD',
            billingPeriod: 'monthly',
            requestsIncluded: 50000,
            features: ['All languages', 'Streaming', 'Speaker diarization'],
          },
        ],
      },
    },
    reputation: {
      score: 91,
      rating: 4.6,
      totalReviews: 123,
      verifiedPayments: 5670,
      uptime: 99.7,
      responseTime: 200,
      successRate: 99.3,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
    ],
    tags: ['speech', 'transcription', 'audio', 'multilingual'],
    endpoint: 'https://api.voiceailabs.io/transcribe',
    status: 'active',
    usageCount: 345000,
    createdAt: new Date('2023-06-01'),
    updatedAt: new Date('2024-01-14'),
    isOnline: true,
    featured: false,
  },
  {
    id: 'svc_8',
    name: 'DeFi Risk Scanner',
    description: 'Automated smart contract security analysis. Detect rug pulls, vulnerabilities, and malicious code patterns.',
    shortDescription: 'Smart contract security analysis API',
    category: 'analytics',
    provider: {
      id: 'prov_8',
      name: 'SecureDeFi',
      walletAddress: '0x8901...2345',
      verified: true,
      reputationScore: 94,
      totalServices: 2,
      joinedAt: new Date('2023-02-10'),
    },
    pricing: {
      type: 'pay-per-use',
      payPerUse: { pricePerRequest: 0.05, currency: 'USD' },
    },
    reputation: {
      score: 94,
      rating: 4.9,
      totalReviews: 89,
      verifiedPayments: 3450,
      uptime: 99.99,
      responseTime: 2500,
      successRate: 99.9,
    },
    badges: [
      { id: 'verified', name: 'Verified', icon: '✓', color: 'green' },
      { id: 'top-rated', name: 'Top Rated', icon: '⭐', color: 'yellow' },
    ],
    tags: ['security', 'defi', 'smart-contract', 'audit', 'risk'],
    endpoint: 'https://api.securedefi.io/scan',
    status: 'active',
    usageCount: 89000,
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2024-01-16'),
    isOnline: true,
    featured: true,
  },
];

export const mockSubscriptions: Subscription[] = [
  {
    id: 'sub_1',
    serviceId: 'svc_2',
    serviceName: 'Crypto Price Oracle',
    subscriberWallet: '0xuser...1234',
    plan: {
      name: 'professional',
      price: 99,
      currency: 'USD',
      billingPeriod: 'monthly',
      requestsIncluded: 100000,
      features: ['500+ tokens', 'WebSocket', 'Priority support', 'Historical data'],
    },
    status: 'active',
    startDate: new Date('2024-01-01'),
    endDate: new Date('2024-02-01'),
    autoRenew: true,
    usageThisMonth: 45230,
    apiKey: 'sk_live_abc123def456',
  },
  {
    id: 'sub_2',
    serviceId: 'svc_4',
    serviceName: 'Trading Signals Pro',
    subscriberWallet: '0xuser...1234',
    plan: {
      name: 'professional',
      price: 199,
      currency: 'USD',
      billingPeriod: 'monthly',
      requestsIncluded: 50000,
      features: ['10 pairs', 'Telegram alerts', 'API access'],
    },
    status: 'active',
    startDate: new Date('2024-01-05'),
    endDate: new Date('2024-02-05'),
    autoRenew: true,
    usageThisMonth: 12450,
    apiKey: 'sk_live_xyz789ghi012',
  },
];

export const mockReviews: ServiceReview[] = [
  {
    id: 'rev_1',
    serviceId: 'svc_1',
    reviewerWallet: '0xrev...1111',
    reviewerName: 'CryptoBuilder',
    rating: 5,
    title: 'Best GPT-4 API wrapper',
    pros: 'Fast, reliable, excellent documentation',
    cons: 'Slightly higher pricing than direct OpenAI',
    useCase: 'Building a crypto trading assistant',
    comment: 'Been using this for 3 months. The streaming support is flawless and the caching really saves costs.',
    createdAt: new Date('2024-01-10'),
    helpful: 24,
    verifiedPurchase: true,
    providerResponse: {
      comment: 'Thank you for the kind review! We work hard to provide the best experience.',
      respondedAt: new Date('2024-01-11'),
    },
  },
  {
    id: 'rev_2',
    serviceId: 'svc_1',
    reviewerWallet: '0xrev...2222',
    reviewerName: 'AIEnthusiast',
    rating: 4,
    title: 'Great service, minor hiccups',
    pros: 'Good uptime, fast response',
    cons: 'Had one outage last month',
    useCase: 'Content generation platform',
    comment: 'Overall very satisfied. The API is well-designed and the team is responsive.',
    createdAt: new Date('2024-01-08'),
    helpful: 12,
    verifiedPurchase: true,
  },
  {
    id: 'rev_3',
    serviceId: 'svc_2',
    reviewerWallet: '0xrev...3333',
    reviewerName: 'TradingBot',
    rating: 5,
    title: 'Essential for my trading bot',
    pros: 'Sub-100ms latency, accurate prices',
    cons: 'None so far',
    useCase: 'Algorithmic trading',
    comment: 'The WebSocket feed is rock solid. Haven\'t missed a tick in 6 months.',
    createdAt: new Date('2024-01-05'),
    helpful: 45,
    verifiedPurchase: true,
  },
];

export const mockPlatformStats: PlatformStats = {
  totalServices: 1247,
  activeProviders: 342,
  totalConsumers: 15680,
  totalApiCalls: 458920000,
  gmv: 2450000,
  platformRevenue: 122500,
  pendingVerifications: 23,
  openDisputes: 7,
};
