/**
 * @file signature-verification.ts
 * @description Cryptographic signature verification implementation
 * @implements x402-gateway.ts#L339 TODO: Verify signature cryptographically
 * @auto-generated by todo-automation
 */

import { createPublicClient, http, verifyMessage, verifyTypedData, recoverMessageAddress } from 'viem';
import { mainnet, sepolia, base, arbitrum, optimism, polygon } from 'viem/chains';
import { keccak256, toBytes, concat, hexToBytes, bytesToHex } from 'viem';
import * as nacl from 'tweetnacl';
import { PublicKey } from '@solana/web3.js';
import bs58 from 'bs58';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface SignatureVerificationResult {
  valid: boolean;
  recoveredAddress?: string;
  error?: string;
  timestamp: number;
  method: 'eip191' | 'eip712' | 'solana' | 'eip1271';
}

export interface EIP712Domain {
  name: string;
  version: string;
  chainId: number;
  verifyingContract: `0x${string}`;
}

export interface PaymentPayload {
  scheme: string;
  network: string;
  maxAmountRequired: string;
  resource: string;
  description: string;
  mimeType: string;
  payTo: string;
  maxTimeoutSeconds: number;
  asset: string;
  extra?: Record<string, unknown>;
}

export interface SignedPayment {
  payload: PaymentPayload;
  signature: string;
  signer: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// EVM Signature Verification
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Verify EIP-191 personal message signature
 */
export async function verifyPersonalSignature(
  message: string,
  signature: `0x${string}`,
  expectedSigner: `0x${string}`
): Promise<SignatureVerificationResult> {
  try {
    const valid = await verifyMessage({
      address: expectedSigner,
      message,
      signature,
    });

    const recoveredAddress = await recoverMessageAddress({
      message,
      signature,
    });

    return {
      valid,
      recoveredAddress,
      timestamp: Date.now(),
      method: 'eip191',
    };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Verification failed',
      timestamp: Date.now(),
      method: 'eip191',
    };
  }
}

/**
 * Verify EIP-712 typed data signature
 */
export async function verifyTypedDataSignature(
  domain: EIP712Domain,
  types: Record<string, Array<{ name: string; type: string }>>,
  primaryType: string,
  message: Record<string, unknown>,
  signature: `0x${string}`,
  expectedSigner: `0x${string}`
): Promise<SignatureVerificationResult> {
  try {
    const valid = await verifyTypedData({
      address: expectedSigner,
      domain,
      types,
      primaryType,
      message,
      signature,
    });

    return {
      valid,
      recoveredAddress: expectedSigner,
      timestamp: Date.now(),
      method: 'eip712',
    };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Verification failed',
      timestamp: Date.now(),
      method: 'eip712',
    };
  }
}

/**
 * Verify x402 payment signature
 */
export async function verifyX402PaymentSignature(
  signedPayment: SignedPayment
): Promise<SignatureVerificationResult> {
  const { payload, signature, signer } = signedPayment;

  // Determine chain type
  if (payload.network.toLowerCase().includes('solana')) {
    return verifySolanaSignature(
      JSON.stringify(payload),
      signature,
      signer
    );
  }

  // EVM signature verification
  const domain: EIP712Domain = {
    name: 'x402 Payment',
    version: '1',
    chainId: getChainId(payload.network),
    verifyingContract: payload.payTo as `0x${string}`,
  };

  const types = {
    Payment: [
      { name: 'scheme', type: 'string' },
      { name: 'network', type: 'string' },
      { name: 'maxAmountRequired', type: 'string' },
      { name: 'resource', type: 'string' },
      { name: 'payTo', type: 'address' },
      { name: 'asset', type: 'address' },
      { name: 'maxTimeoutSeconds', type: 'uint256' },
    ],
  };

  return verifyTypedDataSignature(
    domain,
    types,
    'Payment',
    {
      scheme: payload.scheme,
      network: payload.network,
      maxAmountRequired: payload.maxAmountRequired,
      resource: payload.resource,
      payTo: payload.payTo,
      asset: payload.asset,
      maxTimeoutSeconds: BigInt(payload.maxTimeoutSeconds),
    },
    signature as `0x${string}`,
    signer as `0x${string}`
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// Solana Signature Verification
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Verify Solana Ed25519 signature
 */
export function verifySolanaSignature(
  message: string,
  signature: string,
  publicKeyString: string
): SignatureVerificationResult {
  try {
    // Decode the public key
    const publicKey = new PublicKey(publicKeyString);
    const publicKeyBytes = publicKey.toBytes();

    // Decode the signature (base58 or hex)
    let signatureBytes: Uint8Array;
    if (signature.startsWith('0x')) {
      signatureBytes = hexToBytes(signature as `0x${string}`);
    } else {
      signatureBytes = bs58.decode(signature);
    }

    // Convert message to bytes
    const messageBytes = new TextEncoder().encode(message);

    // Verify using nacl
    const valid = nacl.sign.detached.verify(
      messageBytes,
      signatureBytes,
      publicKeyBytes
    );

    return {
      valid,
      recoveredAddress: publicKeyString,
      timestamp: Date.now(),
      method: 'solana',
    };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Solana verification failed',
      timestamp: Date.now(),
      method: 'solana',
    };
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// EIP-1271 Smart Contract Signature Verification
// ═══════════════════════════════════════════════════════════════════════════

const EIP1271_MAGIC_VALUE = '0x1626ba7e';

const EIP1271_ABI = [
  {
    inputs: [
      { name: 'hash', type: 'bytes32' },
      { name: 'signature', type: 'bytes' },
    ],
    name: 'isValidSignature',
    outputs: [{ name: '', type: 'bytes4' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

/**
 * Verify EIP-1271 smart contract wallet signature
 */
export async function verifyContractSignature(
  message: string,
  signature: `0x${string}`,
  contractAddress: `0x${string}`,
  chainId: number
): Promise<SignatureVerificationResult> {
  try {
    const chain = getChainById(chainId);
    const client = createPublicClient({
      chain,
      transport: http(),
    });

    // Hash the message
    const messageHash = keccak256(toBytes(message));

    // Call isValidSignature on the contract
    const result = await client.readContract({
      address: contractAddress,
      abi: EIP1271_ABI,
      functionName: 'isValidSignature',
      args: [messageHash, signature],
    });

    const valid = result === EIP1271_MAGIC_VALUE;

    return {
      valid,
      recoveredAddress: contractAddress,
      timestamp: Date.now(),
      method: 'eip1271',
    };
  } catch (error) {
    return {
      valid: false,
      error: error instanceof Error ? error.message : 'Contract verification failed',
      timestamp: Date.now(),
      method: 'eip1271',
    };
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Batch Verification
// ═══════════════════════════════════════════════════════════════════════════

export interface BatchVerificationResult {
  total: number;
  valid: number;
  invalid: number;
  results: SignatureVerificationResult[];
}

/**
 * Verify multiple signatures in batch
 */
export async function verifyBatch(
  items: Array<{
    message: string;
    signature: string;
    signer: string;
    type: 'evm' | 'solana';
  }>
): Promise<BatchVerificationResult> {
  const results = await Promise.all(
    items.map(async (item) => {
      if (item.type === 'solana') {
        return verifySolanaSignature(item.message, item.signature, item.signer);
      }
      return verifyPersonalSignature(
        item.message,
        item.signature as `0x${string}`,
        item.signer as `0x${string}`
      );
    })
  );

  return {
    total: results.length,
    valid: results.filter((r) => r.valid).length,
    invalid: results.filter((r) => !r.valid).length,
    results,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════

function getChainId(network: string): number {
  const networkMap: Record<string, number> = {
    mainnet: 1,
    ethereum: 1,
    sepolia: 11155111,
    base: 8453,
    'base-sepolia': 84532,
    arbitrum: 42161,
    'arbitrum-one': 42161,
    optimism: 10,
    polygon: 137,
  };
  return networkMap[network.toLowerCase()] || 1;
}

function getChainById(chainId: number) {
  const chainMap: Record<number, typeof mainnet> = {
    1: mainnet,
    11155111: sepolia,
    8453: base,
    42161: arbitrum,
    10: optimism,
    137: polygon,
  };
  return chainMap[chainId] || mainnet;
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export const signatureVerification = {
  verifyPersonalSignature,
  verifyTypedDataSignature,
  verifyX402PaymentSignature,
  verifySolanaSignature,
  verifyContractSignature,
  verifyBatch,
};

export default signatureVerification;
