/**
 * API Reference Loader
 * 
 * Enterprise-grade loader for API documentation generated by TypeDoc.
 * Provides utilities for loading, parsing, searching, and navigating API symbols.
 * 
 * @packageDocumentation
 */

import fs from 'fs/promises'
import path from 'path'
import matter from 'gray-matter'

// ============================================================================
// Path Configuration
// ============================================================================

const WORKSPACE_ROOT = path.join(process.cwd(), '..')
const API_CONTENT_PATH = path.join(WORKSPACE_ROOT, 'docs/content/api')
const API_REFERENCE_PATH = path.join(WORKSPACE_ROOT, 'docs/api-reference')
const PACKAGES_PATH = path.join(WORKSPACE_ROOT, 'packages')

// ============================================================================
// Type Definitions
// ============================================================================

export type ApiSymbolKind = 
  | 'module'
  | 'namespace'
  | 'class'
  | 'interface'
  | 'type'
  | 'function'
  | 'variable'
  | 'enum'
  | 'enumMember'
  | 'method'
  | 'property'
  | 'constructor'
  | 'accessor'
  | 'getSignature'
  | 'setSignature'
  | 'callSignature'
  | 'indexSignature'

export interface ApiParameter {
  name: string
  type: string
  description?: string
  optional: boolean
  defaultValue?: string
  rest?: boolean
}

export interface ApiTypeParameter {
  name: string
  constraint?: string
  default?: string
  description?: string
}

export interface ApiSymbol {
  id: string
  name: string
  kind: ApiSymbolKind
  package: string
  module?: string
  signature?: string
  description?: string
  parameters?: ApiParameter[]
  typeParameters?: ApiTypeParameter[]
  returnType?: string
  returnDescription?: string
  examples?: string[]
  tags?: Record<string, string>
  sourceFile?: string
  sourceLine?: number
  deprecated?: string | boolean
  since?: string
  see?: string[]
  throws?: Array<{ type: string; description: string }>
  inherits?: string
  implements?: string[]
  members?: ApiSymbol[]
}

export interface ApiPackageInfo {
  name: string
  displayName: string
  version: string
  description: string
  category: string
  keywords: string[]
  repository?: string
  license?: string
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  exports: string[]
  entryPoints: string[]
  symbolCount: number
}

export interface ApiDocPage {
  slug: string
  title: string
  description: string
  package: string
  category: string
  content: string
  toc: TocItem[]
  symbols: ApiSymbol[]
  metadata: Record<string, unknown>
  lastModified?: string
}

export interface TocItem {
  id: string
  title: string
  level: number
  children?: TocItem[]
}

export interface ApiCategory {
  id: string
  name: string
  slug: string
  description: string
  icon: string
  packages: ApiPackageInfo[]
  order: number
}

export interface ApiSearchResult {
  symbol: ApiSymbol
  score: number
  highlights: {
    field: string
    matches: string[]
  }[]
}

// ============================================================================
// Category Configuration
// ============================================================================

export const API_CATEGORIES: Record<string, Omit<ApiCategory, 'packages'>> = {
  core: {
    id: 'core',
    name: 'Core & Infrastructure',
    slug: 'core',
    description: 'Core MCP functionality, shared utilities, type definitions, and infrastructure components.',
    icon: '🏗️',
    order: 1,
  },
  defi: {
    id: 'defi',
    name: 'DeFi Protocols',
    slug: 'defi',
    description: 'DeFi protocol integrations including Uniswap, Aave, Compound, Curve, GMX, Lido, and Yearn.',
    icon: '💰',
    order: 2,
  },
  wallets: {
    id: 'wallets',
    name: 'Wallets & Identity',
    slug: 'wallets',
    description: 'Multi-chain wallet management for EVM, Solana, multi-sig (Safe), ENS, and WalletConnect.',
    icon: '👛',
    order: 3,
  },
  trading: {
    id: 'trading',
    name: 'Trading & CEX',
    slug: 'trading',
    description: 'Centralized exchange integrations (Binance) and automated trading bots.',
    icon: '📈',
    order: 4,
  },
  'market-data': {
    id: 'market-data',
    name: 'Market Data',
    slug: 'market-data',
    description: 'Price feeds, analytics, indicators, and data aggregation from 17+ sources.',
    icon: '📊',
    order: 5,
  },
  agents: {
    id: 'agents',
    name: 'AI Agents',
    slug: 'agents',
    description: 'AI agent frameworks including Agenti, UCAI, and specialized DeFi agents.',
    icon: '🤖',
    order: 6,
  },
  payments: {
    id: 'payments',
    name: 'Payments & x402',
    slug: 'payments',
    description: 'x402 protocol implementation for machine-to-machine micropayments.',
    icon: '💳',
    order: 7,
  },
  nft: {
    id: 'nft',
    name: 'NFT & Gaming',
    slug: 'nft',
    description: 'NFT marketplace integrations (OpenSea, Blur) and gaming assets (Axie).',
    icon: '🎨',
    order: 8,
  },
  security: {
    id: 'security',
    name: 'Security',
    slug: 'security',
    description: 'Chain awareness, MEV protection, rugpull detection, and security analysis.',
    icon: '🔒',
    order: 9,
  },
  novel: {
    id: 'novel',
    name: 'Novel Primitives',
    slug: 'novel',
    description: 'Experimental features: temporal oracles, reputation graphs, privacy pools, quantum-resistant signatures.',
    icon: '🧪',
    order: 10,
  },
  automation: {
    id: 'automation',
    name: 'Automation',
    slug: 'automation',
    description: 'Social media automation, monitoring, and automated trading volume tools.',
    icon: '⚙️',
    order: 11,
  },
  marketplace: {
    id: 'marketplace',
    name: 'Marketplace',
    slug: 'marketplace',
    description: 'AI service marketplace, credits system, and agent wallet.',
    icon: '🏪',
    order: 12,
  },
}

// ============================================================================
// Symbol Kind Configuration
// ============================================================================

export const SYMBOL_KIND_CONFIG: Record<ApiSymbolKind, { icon: string; label: string; color: string }> = {
  module: { icon: '📦', label: 'Module', color: 'blue' },
  namespace: { icon: '📁', label: 'Namespace', color: 'blue' },
  class: { icon: '🏛️', label: 'Class', color: 'purple' },
  interface: { icon: '📋', label: 'Interface', color: 'green' },
  type: { icon: '🏷️', label: 'Type', color: 'cyan' },
  function: { icon: '⚡', label: 'Function', color: 'yellow' },
  variable: { icon: '📌', label: 'Variable', color: 'orange' },
  enum: { icon: '🔢', label: 'Enum', color: 'pink' },
  enumMember: { icon: '•', label: 'Enum Member', color: 'pink' },
  method: { icon: '🔧', label: 'Method', color: 'indigo' },
  property: { icon: '🔑', label: 'Property', color: 'teal' },
  constructor: { icon: '🔨', label: 'Constructor', color: 'red' },
  accessor: { icon: '🔄', label: 'Accessor', color: 'gray' },
  getSignature: { icon: '📤', label: 'Getter', color: 'gray' },
  setSignature: { icon: '📥', label: 'Setter', color: 'gray' },
  callSignature: { icon: '📞', label: 'Call Signature', color: 'yellow' },
  indexSignature: { icon: '🔍', label: 'Index Signature', color: 'gray' },
}

// ============================================================================
// File System Utilities
// ============================================================================

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}

async function readJsonFile<T>(filePath: string): Promise<T | null> {
  try {
    const content = await fs.readFile(filePath, 'utf-8')
    return JSON.parse(content) as T
  } catch {
    return null
  }
}

async function getFilesRecursive(dir: string, pattern?: RegExp): Promise<string[]> {
  const files: string[] = []
  
  try {
    const entries = await fs.readdir(dir, { withFileTypes: true })
    
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      
      if (entry.isDirectory()) {
        if (entry.name !== 'node_modules' && !entry.name.startsWith('.')) {
          files.push(...await getFilesRecursive(fullPath, pattern))
        }
      } else if (!pattern || pattern.test(entry.name)) {
        files.push(fullPath)
      }
    }
  } catch {
    // Directory doesn't exist or not readable
  }
  
  return files
}

// ============================================================================
// Package Discovery
// ============================================================================

interface PackageJson {
  name: string
  version?: string
  description?: string
  keywords?: string[]
  license?: string
  repository?: string | { url: string }
  dependencies?: Record<string, string>
  peerDependencies?: Record<string, string>
  main?: string
  types?: string
  exports?: Record<string, unknown>
}

async function discoverPackages(): Promise<ApiPackageInfo[]> {
  const packages: ApiPackageInfo[] = []
  const packageJsonFiles = await getFilesRecursive(PACKAGES_PATH, /^package\.json$/)
  
  for (const pkgJsonPath of packageJsonFiles) {
    const pkgJson = await readJsonFile<PackageJson>(pkgJsonPath)
    if (!pkgJson || !pkgJson.name) continue
    
    const pkgDir = path.dirname(pkgJsonPath)
    const relativePath = path.relative(PACKAGES_PATH, pkgDir)
    const category = getCategoryFromPath(relativePath)
    
    // Find entry points
    const srcDir = path.join(pkgDir, 'src')
    const entryPoints: string[] = []
    
    if (await pathExists(srcDir)) {
      for (const entry of ['index.ts', 'index.tsx', 'main.ts']) {
        if (await pathExists(path.join(srcDir, entry))) {
          entryPoints.push(path.join(srcDir, entry))
          break
        }
      }
    }
    
    // Count TypeScript files as proxy for symbol count
    const tsFiles = await getFilesRecursive(pkgDir, /\.(ts|tsx)$/)
    const symbolCount = tsFiles.length * 10 // Rough estimate
    
    // Extract exports from package.json
    const exports: string[] = []
    if (pkgJson.exports) {
      if (typeof pkgJson.exports === 'object') {
        exports.push(...Object.keys(pkgJson.exports).filter(k => !k.startsWith('.')))
      }
    }
    if (pkgJson.main) exports.push('default')
    
    packages.push({
      name: pkgJson.name,
      displayName: pkgJson.name.replace(/^@[^/]+\//, ''),
      version: pkgJson.version || '0.0.0',
      description: pkgJson.description || '',
      category,
      keywords: pkgJson.keywords || [],
      license: pkgJson.license,
      repository: typeof pkgJson.repository === 'string' 
        ? pkgJson.repository 
        : pkgJson.repository?.url,
      dependencies: pkgJson.dependencies,
      peerDependencies: pkgJson.peerDependencies,
      exports,
      entryPoints,
      symbolCount,
    })
  }
  
  return packages.sort((a, b) => a.displayName.localeCompare(b.displayName))
}

function getCategoryFromPath(relativePath: string): string {
  const parts = relativePath.split(path.sep)
  const firstPart = parts[0]?.toLowerCase()
  
  if (firstPart && API_CATEGORIES[firstPart]) {
    return firstPart
  }
  
  // Map common package locations to categories
  const categoryMappings: Record<string, string> = {
    'core': 'core',
    'shared': 'core',
    'infrastructure': 'core',
    'defi': 'defi',
    'wallets': 'wallets',
    'trading': 'trading',
    'market-data': 'market-data',
    'agents': 'agents',
    'payments': 'payments',
    'nft': 'nft',
    'security': 'security',
    'novel': 'novel',
    'automation': 'automation',
    'marketplace': 'marketplace',
    'credits': 'marketplace',
    'agent-wallet': 'marketplace',
    'dashboard': 'core',
    'generators': 'automation',
    'integrations': 'core',
  }
  
  return categoryMappings[firstPart] || 'core'
}

// ============================================================================
// API Documentation Loading
// ============================================================================

export async function getAllApiDocs(): Promise<ApiDocPage[]> {
  const files = await getFilesRecursive(API_CONTENT_PATH, /\.(md|mdx)$/)
  const docs: ApiDocPage[] = []
  
  for (const filePath of files) {
    try {
      const content = await fs.readFile(filePath, 'utf-8')
      const { data, content: body } = matter(content)
      
      const relativePath = path.relative(API_CONTENT_PATH, filePath)
      const slug = relativePath
        .replace(/\.(md|mdx)$/, '')
        .replace(/\\/g, '/')
        .replace(/\/index$/, '')
      
      // Extract TOC from content
      const toc = extractTableOfContents(body)
      
      // Get file stats for lastModified
      const stats = await fs.stat(filePath)
      
      docs.push({
        slug,
        title: data.title || formatTitle(slug),
        description: data.description || '',
        package: data.package || extractPackageFromSlug(slug),
        category: data.category || 'api',
        content: body,
        toc,
        symbols: data.symbols || [],
        metadata: data,
        lastModified: stats.mtime.toISOString(),
      })
    } catch (error) {
      console.error(`Error loading API doc ${filePath}:`, error)
    }
  }
  
  return docs.sort((a, b) => a.title.localeCompare(b.title))
}

export async function getApiDocBySlug(slug: string): Promise<ApiDocPage | null> {
  const possiblePaths = [
    path.join(API_CONTENT_PATH, `${slug}.md`),
    path.join(API_CONTENT_PATH, `${slug}.mdx`),
    path.join(API_CONTENT_PATH, slug, 'index.md'),
    path.join(API_CONTENT_PATH, slug, 'index.mdx'),
    path.join(API_CONTENT_PATH, slug, 'README.md'),
  ]
  
  for (const filePath of possiblePaths) {
    if (await pathExists(filePath)) {
      try {
        const content = await fs.readFile(filePath, 'utf-8')
        const { data, content: body } = matter(content)
        const toc = extractTableOfContents(body)
        const stats = await fs.stat(filePath)
        
        return {
          slug,
          title: data.title || formatTitle(slug),
          description: data.description || '',
          package: data.package || extractPackageFromSlug(slug),
          category: data.category || 'api',
          content: body,
          toc,
          symbols: data.symbols || [],
          metadata: data,
          lastModified: stats.mtime.toISOString(),
        }
      } catch {
        continue
      }
    }
  }
  
  return null
}

export async function getAllApiDocSlugs(): Promise<string[]> {
  const docs = await getAllApiDocs()
  return docs.map(doc => doc.slug)
}

// ============================================================================
// Helper Functions
// ============================================================================

function extractTableOfContents(content: string): TocItem[] {
  const toc: TocItem[] = []
  const headingRegex = /^(#{2,4})\s+(.+)$/gm
  let match
  
  while ((match = headingRegex.exec(content)) !== null) {
    const level = match[1].length
    const title = match[2].replace(/`/g, '').trim()
    const id = title
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-')
    
    toc.push({ id, title, level })
  }
  
  return buildTocTree(toc)
}

function buildTocTree(items: TocItem[]): TocItem[] {
  const result: TocItem[] = []
  const stack: TocItem[] = []
  
  for (const item of items) {
    const newItem = { ...item, children: [] }
    
    while (stack.length > 0 && stack[stack.length - 1].level >= item.level) {
      stack.pop()
    }
    
    if (stack.length === 0) {
      result.push(newItem)
    } else {
      const parent = stack[stack.length - 1]
      if (!parent.children) parent.children = []
      parent.children.push(newItem)
    }
    
    stack.push(newItem)
  }
  
  return result
}

function formatTitle(slug: string): string {
  const name = slug.split('/').pop() || slug
  return name
    .replace(/-/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase())
}

function extractPackageFromSlug(slug: string): string {
  const parts = slug.split('/')
  return parts[0] || 'unknown'
}

// ============================================================================
// Symbol Search
// ============================================================================

let symbolCache: ApiSymbol[] | null = null

export async function getAllApiSymbols(): Promise<ApiSymbol[]> {
  if (symbolCache) return symbolCache
  
  // Try to load from pre-built index
  const indexPath = path.join(API_CONTENT_PATH, 'search-index.json')
  if (await pathExists(indexPath)) {
    const data = await readJsonFile<ApiSymbol[]>(indexPath)
    if (data) {
      symbolCache = data
      return data
    }
  }
  
  // Extract symbols from TypeDoc JSON output
  const typedocJsonPath = path.join(API_REFERENCE_PATH, 'api.json')
  if (await pathExists(typedocJsonPath)) {
    const typedocData = await readJsonFile<TypeDocProject>(typedocJsonPath)
    if (typedocData) {
      symbolCache = extractSymbolsFromTypedoc(typedocData)
      return symbolCache
    }
  }
  
  // Fall back to extracting from markdown docs
  const docs = await getAllApiDocs()
  const symbols: ApiSymbol[] = []
  
  for (const doc of docs) {
    symbols.push(...extractSymbolsFromMarkdown(doc))
  }
  
  symbolCache = symbols
  return symbols
}

interface TypeDocProject {
  id: number
  name: string
  kind: number
  children?: TypeDocReflection[]
}

interface TypeDocReflection {
  id: number
  name: string
  kind: number
  comment?: { summary?: Array<{ text: string }> }
  signatures?: TypeDocSignature[]
  children?: TypeDocReflection[]
  sources?: Array<{ fileName: string; line: number }>
  type?: TypeDocType
}

interface TypeDocSignature {
  id: number
  name: string
  kind: number
  parameters?: TypeDocParameter[]
  type?: TypeDocType
  comment?: { summary?: Array<{ text: string }> }
}

interface TypeDocParameter {
  id: number
  name: string
  type?: TypeDocType
  flags?: { isOptional?: boolean; isRest?: boolean }
  defaultValue?: string
  comment?: { summary?: Array<{ text: string }> }
}

interface TypeDocType {
  type: string
  name?: string
  value?: unknown
  types?: TypeDocType[]
  declaration?: TypeDocReflection
}

const TYPEDOC_KIND_MAP: Record<number, ApiSymbolKind> = {
  1: 'module',
  2: 'namespace',
  4: 'enum',
  8: 'enumMember',
  16: 'variable',
  32: 'function',
  64: 'class',
  128: 'interface',
  256: 'constructor',
  512: 'property',
  1024: 'method',
  2048: 'callSignature',
  4096: 'indexSignature',
  8192: 'constructor',
  65536: 'type',
  131072: 'accessor',
  262144: 'getSignature',
  524288: 'setSignature',
  1048576: 'type',
}

function extractSymbolsFromTypedoc(project: TypeDocProject): ApiSymbol[] {
  const symbols: ApiSymbol[] = []
  
  function processReflection(reflection: TypeDocReflection, packageName: string, parentPath: string = ''): void {
    const kind = TYPEDOC_KIND_MAP[reflection.kind]
    if (!kind) return
    
    const currentPath = parentPath ? `${parentPath}.${reflection.name}` : reflection.name
    const description = reflection.comment?.summary?.map(s => s.text).join('') || undefined
    
    const symbol: ApiSymbol = {
      id: `${packageName}-${reflection.id}`,
      name: reflection.name,
      kind,
      package: packageName,
      description,
      sourceFile: reflection.sources?.[0]?.fileName,
      sourceLine: reflection.sources?.[0]?.line,
    }
    
    // Extract parameters from signatures
    if (reflection.signatures?.[0]) {
      const sig = reflection.signatures[0]
      symbol.parameters = sig.parameters?.map(p => ({
        name: p.name,
        type: typeToString(p.type),
        description: p.comment?.summary?.map(s => s.text).join(''),
        optional: p.flags?.isOptional || false,
        rest: p.flags?.isRest,
        defaultValue: p.defaultValue,
      }))
      symbol.returnType = typeToString(sig.type)
      symbol.description = symbol.description || sig.comment?.summary?.map(s => s.text).join('')
    }
    
    symbols.push(symbol)
    
    // Process children
    if (reflection.children) {
      for (const child of reflection.children) {
        processReflection(child, packageName, currentPath)
      }
    }
  }
  
  if (project.children) {
    for (const pkg of project.children) {
      processReflection(pkg, pkg.name)
    }
  }
  
  return symbols
}

function typeToString(type?: TypeDocType): string {
  if (!type) return 'unknown'
  
  switch (type.type) {
    case 'intrinsic':
    case 'reference':
      return type.name || 'unknown'
    case 'literal':
      return JSON.stringify(type.value)
    case 'union':
      return type.types?.map(t => typeToString(t)).join(' | ') || 'unknown'
    case 'array':
      return `${typeToString(type.types?.[0])}[]`
    default:
      return type.name || 'unknown'
  }
}

function extractSymbolsFromMarkdown(doc: ApiDocPage): ApiSymbol[] {
  const symbols: ApiSymbol[] = []
  const content = doc.content
  
  // Match class definitions
  const classRegex = /^##\s+(?:Class|class):\s*`?(\w+)`?/gm
  let match
  while ((match = classRegex.exec(content)) !== null) {
    symbols.push({
      id: `${doc.package}-class-${match[1]}`,
      name: match[1],
      kind: 'class',
      package: doc.package,
    })
  }
  
  // Match interface definitions
  const interfaceRegex = /^##\s+(?:Interface|interface):\s*`?(\w+)`?/gm
  while ((match = interfaceRegex.exec(content)) !== null) {
    symbols.push({
      id: `${doc.package}-interface-${match[1]}`,
      name: match[1],
      kind: 'interface',
      package: doc.package,
    })
  }
  
  // Match function definitions
  const funcRegex = /^##\s+(?:Function|function):\s*`?(\w+)`?/gm
  while ((match = funcRegex.exec(content)) !== null) {
    symbols.push({
      id: `${doc.package}-function-${match[1]}`,
      name: match[1],
      kind: 'function',
      package: doc.package,
    })
  }
  
  // Match type definitions
  const typeRegex = /^##\s+(?:Type|type|TypeAlias):\s*`?(\w+)`?/gm
  while ((match = typeRegex.exec(content)) !== null) {
    symbols.push({
      id: `${doc.package}-type-${match[1]}`,
      name: match[1],
      kind: 'type',
      package: doc.package,
    })
  }
  
  return symbols
}

export async function searchApiSymbols(
  query: string,
  options?: {
    kind?: ApiSymbolKind[]
    package?: string
    category?: string
    limit?: number
  }
): Promise<ApiSearchResult[]> {
  const symbols = await getAllApiSymbols()
  const queryLower = query.toLowerCase().trim()
  
  if (!queryLower) return []
  
  const results: ApiSearchResult[] = []
  
  for (const symbol of symbols) {
    // Apply filters
    if (options?.kind && !options.kind.includes(symbol.kind)) continue
    if (options?.package && symbol.package !== options.package) continue
    
    // Calculate match score
    const nameLower = symbol.name.toLowerCase()
    const descLower = (symbol.description || '').toLowerCase()
    
    let score = 0
    const highlights: ApiSearchResult['highlights'] = []
    
    // Exact name match
    if (nameLower === queryLower) {
      score += 100
      highlights.push({ field: 'name', matches: [symbol.name] })
    }
    // Name starts with query
    else if (nameLower.startsWith(queryLower)) {
      score += 80
      highlights.push({ field: 'name', matches: [symbol.name] })
    }
    // Name contains query
    else if (nameLower.includes(queryLower)) {
      score += 50
      highlights.push({ field: 'name', matches: [symbol.name] })
    }
    // Description contains query
    else if (descLower.includes(queryLower)) {
      score += 20
      highlights.push({ field: 'description', matches: [symbol.description!] })
    }
    else {
      continue // No match
    }
    
    // Boost score for certain kinds
    if (symbol.kind === 'class' || symbol.kind === 'function') {
      score += 10
    }
    
    results.push({ symbol, score, highlights })
  }
  
  // Sort by score descending
  results.sort((a, b) => b.score - a.score)
  
  // Apply limit
  if (options?.limit) {
    return results.slice(0, options.limit)
  }
  
  return results
}

// ============================================================================
// Categories & Packages
// ============================================================================

export async function getAllApiPackages(): Promise<ApiPackageInfo[]> {
  return discoverPackages()
}

export async function getApiPackagesByCategory(): Promise<ApiCategory[]> {
  const packages = await discoverPackages()
  const categoryMap = new Map<string, ApiCategory>()
  
  for (const pkg of packages) {
    const categoryConfig = API_CATEGORIES[pkg.category]
    if (!categoryConfig) continue
    
    if (!categoryMap.has(pkg.category)) {
      categoryMap.set(pkg.category, {
        ...categoryConfig,
        packages: [],
      })
    }
    
    categoryMap.get(pkg.category)!.packages.push(pkg)
  }
  
  return Array.from(categoryMap.values())
    .sort((a, b) => a.order - b.order)
}

export async function getApiPackage(name: string): Promise<ApiPackageInfo | null> {
  const packages = await discoverPackages()
  return packages.find(p => p.name === name || p.displayName === name) || null
}

// ============================================================================
// Navigation
// ============================================================================

export interface ApiNavItem {
  title: string
  href: string
  description?: string
  badge?: string
  icon?: string
  items?: ApiNavItem[]
}

export async function getApiNavigation(): Promise<ApiNavItem[]> {
  const categories = await getApiPackagesByCategory()
  
  return categories.map(category => ({
    title: category.name,
    href: `/docs/api/${category.slug}`,
    description: category.description,
    icon: category.icon,
    badge: `${category.packages.length}`,
    items: category.packages.map(pkg => ({
      title: pkg.displayName,
      href: `/docs/api/${pkg.displayName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
      description: pkg.description,
    })),
  }))
}

// ============================================================================
// Statistics
// ============================================================================

export interface ApiStats {
  totalPackages: number
  totalSymbols: number
  categoryCounts: Record<string, number>
  kindCounts: Record<string, number>
}

export async function getApiStats(): Promise<ApiStats> {
  const packages = await discoverPackages()
  const symbols = await getAllApiSymbols()
  
  const categoryCounts: Record<string, number> = {}
  for (const pkg of packages) {
    categoryCounts[pkg.category] = (categoryCounts[pkg.category] || 0) + 1
  }
  
  const kindCounts: Record<string, number> = {}
  for (const symbol of symbols) {
    kindCounts[symbol.kind] = (kindCounts[symbol.kind] || 0) + 1
  }
  
  return {
    totalPackages: packages.length,
    totalSymbols: symbols.length,
    categoryCounts,
    kindCounts,
  }
}
