/**
 * Railway deployment configuration generation
 * Generates railway.json and railway.toml configurations
 */

import { X402Config } from "../types/config.js";

/**
 * Railway configuration interface
 */
export interface RailwayConfig {
  $schema: string;
  build: {
    builder: string;
    dockerfilePath?: string;
    buildCommand?: string;
    watchPatterns?: string[];
  };
  deploy: {
    numReplicas?: number;
    startCommand?: string;
    healthcheckPath?: string;
    healthcheckTimeout?: number;
    restartPolicyType?: "ON_FAILURE" | "ALWAYS" | "NEVER";
    restartPolicyMaxRetries?: number;
  };
}

/**
 * Generate railway.json configuration
 */
export function generateRailwayJson(config: X402Config): string {
  const scaling = config.deploy?.scaling || { min: 1, max: 10 };

  const railwayConfig: RailwayConfig = {
    $schema: "https://railway.app/railway.schema.json",
    build: {
      builder: "DOCKERFILE",
      dockerfilePath: "Dockerfile",
      watchPatterns: ["src/**", "package.json", "x402.config.json"],
    },
    deploy: {
      numReplicas: scaling.min,
      startCommand: "node .x402/wrapper.js",
      healthcheckPath: "/health",
      healthcheckTimeout: 30,
      restartPolicyType: "ON_FAILURE",
      restartPolicyMaxRetries: 5,
    },
  };

  return JSON.stringify(railwayConfig, null, 2);
}

/**
 * Generate railway.toml configuration (alternative format)
 */
export function generateRailwayToml(config: X402Config): string {
  const scaling = config.deploy?.scaling || { min: 1, max: 10 };

  return `# Auto-generated by x402-deploy
# Project: ${config.name}

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["src/**", "package.json", "x402.config.json"]

[deploy]
numReplicas = ${scaling.min}
startCommand = "node .x402/wrapper.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
`;
}

/**
 * Generate environment variables for Railway
 */
export function generateRailwayEnvVars(config: X402Config): Record<string, string> {
  const envVars: Record<string, string> = {
    NODE_ENV: "production",
    X402_ENABLED: "true",
    X402_WALLET: config.payment.wallet,
    X402_NETWORK: config.payment.network,
    X402_TOKEN: config.payment.token || "USDC",
    X402_PRICING_MODEL: config.pricing.model,
    X402_DEFAULT_PRICE: config.pricing.default || "$0.001",
  };

  // Add facilitator if configured
  if (config.payment.facilitator) {
    envVars.X402_FACILITATOR_URL = config.payment.facilitator;
  }

  // Add discovery settings
  if (config.discovery?.enabled !== false) {
    envVars.X402_DISCOVERY_ENABLED = "true";
    if (config.discovery?.autoRegister !== false) {
      envVars.X402_AUTO_REGISTER = "true";
    }
  }

  // Add custom env vars from config
  if (config.deploy?.env) {
    Object.assign(envVars, config.deploy.env);
  }

  return envVars;
}

/**
 * Railway service configuration for multi-service projects
 */
export interface RailwayServiceConfig {
  name: string;
  source: {
    repo?: string;
    branch?: string;
    rootDirectory?: string;
  };
  variables: Record<string, string>;
  networking?: {
    serviceDomains?: {
      hasCert: boolean;
    };
  };
}

/**
 * Generate Railway service configuration for Nixpacks (without Docker)
 */
export function generateRailwayNixpacksConfig(config: X402Config): string {
  return `# Auto-generated by x402-deploy
# Nixpacks configuration for Railway

[phases.setup]
aptPkgs = ["..."]

[phases.install]
cmds = [
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node .x402/wrapper.js"
`;
}

/**
 * Generate Procfile for Railway
 */
export function generateProcfile(config: X402Config): string {
  const projectType = config.type || "unknown";

  switch (projectType) {
    case "fastapi":
      return `web: python .x402/wrapper.py`;
    case "nextjs":
      return `web: node .x402/wrapper.js`;
    default:
      return `web: node .x402/wrapper.js`;
  }
}
