# ═══════════════════════════════════════════════════════════════
#  universal-crypto-mcp | nich
#  ID: 0x4E494348
# ═══════════════════════════════════════════════════════════════

# You can remove this file if you don't want to use Yarn package manager.
nodeLinker: node-modules


# universal-crypto-mcp © nichxbt