/**
 * @file aggregator.ts
 * @description Multi-source price aggregation with fallback
 * @implements workers.ts#L96 TODO: Implement price fetching from CoinGecko/DeFiLlama
 * @auto-generated by todo-automation
 */

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface PriceData {
  symbol: string;
  price: number;
  priceUsd: number;
  change24h: number;
  volume24h: number;
  marketCap: number;
  lastUpdated: number;
  source: PriceSource;
  confidence: number;
}

export enum PriceSource {
  COINGECKO = 'coingecko',
  DEFILLAMA = 'defillama',
  CHAINLINK = 'chainlink',
  UNISWAP = 'uniswap',
  BINANCE = 'binance',
  AGGREGATED = 'aggregated',
}

export interface PriceAggregatorConfig {
  sources: PriceSource[];
  cacheTtlMs: number;
  maxStaleMs: number;
  minConfidence: number;
  useMedian: boolean;
}

interface CacheEntry {
  data: PriceData;
  timestamp: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// Price Fetchers
// ═══════════════════════════════════════════════════════════════════════════

async function fetchFromCoinGecko(tokenId: string): Promise<PriceData | null> {
  try {
    const response = await fetch(
      `https://api.coingecko.com/api/v3/simple/price?ids=${tokenId}&vs_currencies=usd&include_24hr_change=true&include_24hr_vol=true&include_market_cap=true`,
      {
        headers: {
          'Accept': 'application/json',
        },
      }
    );

    if (!response.ok) return null;

    const data = await response.json();
    const tokenData = data[tokenId];
    
    if (!tokenData) return null;

    return {
      symbol: tokenId,
      price: tokenData.usd,
      priceUsd: tokenData.usd,
      change24h: tokenData.usd_24h_change || 0,
      volume24h: tokenData.usd_24h_vol || 0,
      marketCap: tokenData.usd_market_cap || 0,
      lastUpdated: Date.now(),
      source: PriceSource.COINGECKO,
      confidence: 0.95,
    };
  } catch (error) {
    console.error('[CoinGecko] Error fetching price:', error);
    return null;
  }
}

async function fetchFromDefiLlama(tokenAddress: string, chain: string = 'ethereum'): Promise<PriceData | null> {
  try {
    const coinId = `${chain}:${tokenAddress}`;
    const response = await fetch(
      `https://coins.llama.fi/prices/current/${coinId}`,
      {
        headers: {
          'Accept': 'application/json',
        },
      }
    );

    if (!response.ok) return null;

    const data = await response.json();
    const coin = data.coins?.[coinId];
    
    if (!coin) return null;

    return {
      symbol: coin.symbol || tokenAddress,
      price: coin.price,
      priceUsd: coin.price,
      change24h: 0, // DeFiLlama doesn't provide this directly
      volume24h: 0,
      marketCap: 0,
      lastUpdated: coin.timestamp * 1000 || Date.now(),
      source: PriceSource.DEFILLAMA,
      confidence: coin.confidence || 0.9,
    };
  } catch (error) {
    console.error('[DeFiLlama] Error fetching price:', error);
    return null;
  }
}

async function fetchFromBinance(symbol: string): Promise<PriceData | null> {
  try {
    const pair = `${symbol.toUpperCase()}USDT`;
    const [tickerRes, statsRes] = await Promise.all([
      fetch(`https://api.binance.com/api/v3/ticker/price?symbol=${pair}`),
      fetch(`https://api.binance.com/api/v3/ticker/24hr?symbol=${pair}`),
    ]);

    if (!tickerRes.ok || !statsRes.ok) return null;

    const ticker = await tickerRes.json();
    const stats = await statsRes.json();

    return {
      symbol,
      price: parseFloat(ticker.price),
      priceUsd: parseFloat(ticker.price),
      change24h: parseFloat(stats.priceChangePercent),
      volume24h: parseFloat(stats.volume) * parseFloat(ticker.price),
      marketCap: 0,
      lastUpdated: Date.now(),
      source: PriceSource.BINANCE,
      confidence: 0.98,
    };
  } catch (error) {
    console.error('[Binance] Error fetching price:', error);
    return null;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Price Aggregator Service
// ═══════════════════════════════════════════════════════════════════════════

export class PriceAggregator {
  private cache: Map<string, CacheEntry> = new Map();
  private config: PriceAggregatorConfig;

  constructor(config?: Partial<PriceAggregatorConfig>) {
    this.config = {
      sources: [PriceSource.COINGECKO, PriceSource.DEFILLAMA, PriceSource.BINANCE],
      cacheTtlMs: 30000, // 30 seconds
      maxStaleMs: 300000, // 5 minutes
      minConfidence: 0.8,
      useMedian: true,
      ...config,
    };
  }

  /**
   * Get aggregated price from multiple sources
   */
  async getPrice(identifier: string, options?: {
    chain?: string;
    forceRefresh?: boolean;
  }): Promise<PriceData | null> {
    const cacheKey = `${identifier}:${options?.chain || 'default'}`;
    
    // Check cache first
    if (!options?.forceRefresh) {
      const cached = this.cache.get(cacheKey);
      if (cached && Date.now() - cached.timestamp < this.config.cacheTtlMs) {
        return cached.data;
      }
    }

    // Fetch from all configured sources
    const prices = await this.fetchFromAllSources(identifier, options?.chain);
    
    if (prices.length === 0) {
      // Return stale cache if available
      const stale = this.cache.get(cacheKey);
      if (stale && Date.now() - stale.timestamp < this.config.maxStaleMs) {
        return { ...stale.data, confidence: stale.data.confidence * 0.5 };
      }
      return null;
    }

    // Aggregate prices
    const aggregated = this.aggregatePrices(prices, identifier);
    
    // Cache the result
    this.cache.set(cacheKey, {
      data: aggregated,
      timestamp: Date.now(),
    });

    return aggregated;
  }

  /**
   * Get prices for multiple tokens
   */
  async getPrices(identifiers: string[]): Promise<Map<string, PriceData | null>> {
    const results = await Promise.all(
      identifiers.map(async (id) => ({
        id,
        data: await this.getPrice(id),
      }))
    );

    return new Map(results.map(({ id, data }) => [id, data]));
  }

  /**
   * Fetch from all configured sources
   */
  private async fetchFromAllSources(identifier: string, chain?: string): Promise<PriceData[]> {
    const fetchers: Promise<PriceData | null>[] = [];

    for (const source of this.config.sources) {
      switch (source) {
        case PriceSource.COINGECKO:
          fetchers.push(fetchFromCoinGecko(identifier));
          break;
        case PriceSource.DEFILLAMA:
          if (identifier.startsWith('0x')) {
            fetchers.push(fetchFromDefiLlama(identifier, chain));
          }
          break;
        case PriceSource.BINANCE:
          fetchers.push(fetchFromBinance(identifier));
          break;
      }
    }

    const results = await Promise.allSettled(fetchers);
    
    return results
      .filter((r): r is PromiseFulfilledResult<PriceData | null> => r.status === 'fulfilled')
      .map((r) => r.value)
      .filter((data): data is PriceData => data !== null && data.confidence >= this.config.minConfidence);
  }

  /**
   * Aggregate prices using median or weighted average
   */
  private aggregatePrices(prices: PriceData[], symbol: string): PriceData {
    if (prices.length === 1) return prices[0];

    const priceValues = prices.map((p) => p.price).sort((a, b) => a - b);
    
    let aggregatedPrice: number;
    
    if (this.config.useMedian) {
      // Median
      const mid = Math.floor(priceValues.length / 2);
      aggregatedPrice = priceValues.length % 2 === 0
        ? (priceValues[mid - 1] + priceValues[mid]) / 2
        : priceValues[mid];
    } else {
      // Weighted average by confidence
      const totalConfidence = prices.reduce((sum, p) => sum + p.confidence, 0);
      aggregatedPrice = prices.reduce(
        (sum, p) => sum + (p.price * p.confidence) / totalConfidence,
        0
      );
    }

    // Calculate deviation to assess confidence
    const deviation = this.calculateDeviation(priceValues, aggregatedPrice);
    const baseConfidence = Math.min(...prices.map((p) => p.confidence));
    const adjustedConfidence = baseConfidence * (1 - Math.min(deviation, 0.2));

    return {
      symbol,
      price: aggregatedPrice,
      priceUsd: aggregatedPrice,
      change24h: this.median(prices.map((p) => p.change24h)),
      volume24h: Math.max(...prices.map((p) => p.volume24h)),
      marketCap: Math.max(...prices.map((p) => p.marketCap)),
      lastUpdated: Date.now(),
      source: PriceSource.AGGREGATED,
      confidence: adjustedConfidence,
    };
  }

  private calculateDeviation(values: number[], mean: number): number {
    if (values.length < 2) return 0;
    const variance = values.reduce((sum, v) => sum + Math.pow(v - mean, 2), 0) / values.length;
    return Math.sqrt(variance) / mean;
  }

  private median(values: number[]): number {
    const sorted = [...values].sort((a, b) => a - b);
    const mid = Math.floor(sorted.length / 2);
    return sorted.length % 2 === 0
      ? (sorted[mid - 1] + sorted[mid]) / 2
      : sorted[mid];
  }

  /**
   * Clear the price cache
   */
  clearCache(): void {
    this.cache.clear();
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Common Token Mappings
// ═══════════════════════════════════════════════════════════════════════════

export const TOKEN_MAPPINGS: Record<string, { coingecko: string; binance: string }> = {
  ETH: { coingecko: 'ethereum', binance: 'ETH' },
  WETH: { coingecko: 'weth', binance: 'ETH' },
  BTC: { coingecko: 'bitcoin', binance: 'BTC' },
  WBTC: { coingecko: 'wrapped-bitcoin', binance: 'BTC' },
  USDC: { coingecko: 'usd-coin', binance: 'USDC' },
  USDT: { coingecko: 'tether', binance: 'USDT' },
  DAI: { coingecko: 'dai', binance: 'DAI' },
  SOL: { coingecko: 'solana', binance: 'SOL' },
  MATIC: { coingecko: 'matic-network', binance: 'MATIC' },
  ARB: { coingecko: 'arbitrum', binance: 'ARB' },
  OP: { coingecko: 'optimism', binance: 'OP' },
  LINK: { coingecko: 'chainlink', binance: 'LINK' },
  UNI: { coingecko: 'uniswap', binance: 'UNI' },
  AAVE: { coingecko: 'aave', binance: 'AAVE' },
};

// ═══════════════════════════════════════════════════════════════════════════
// Singleton Instance
// ═══════════════════════════════════════════════════════════════════════════

export const priceAggregator = new PriceAggregator();

export default PriceAggregator;
