/**
 * @file refund.ts
 * @description Payment refund implementation
 * @implements facilitator.ts#L457, payment.ts#L405, revenue.ts#L519 TODOs
 * @auto-generated by todo-automation
 */

import {
  createWalletClient,
  createPublicClient,
  http,
  parseUnits,
  formatUnits,
  type Address,
  type Hash,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { mainnet, base, arbitrum, optimism } from 'viem/chains';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface RefundRequest {
  paymentId: string;
  originalTxHash: Hash;
  recipient: Address;
  amount: bigint;
  asset: Address;
  chainId: number;
  reason: RefundReason;
  metadata?: Record<string, unknown>;
}

export enum RefundReason {
  CUSTOMER_REQUEST = 'customer_request',
  SERVICE_UNAVAILABLE = 'service_unavailable',
  DUPLICATE_PAYMENT = 'duplicate_payment',
  FAILED_DELIVERY = 'failed_delivery',
  FRAUD_DETECTED = 'fraud_detected',
  PARTIAL_FULFILLMENT = 'partial_fulfillment',
  OVERPAYMENT = 'overpayment',
}

export enum RefundStatus {
  PENDING = 'pending',
  PROCESSING = 'processing',
  COMPLETED = 'completed',
  FAILED = 'failed',
  CANCELLED = 'cancelled',
}

export interface RefundResult {
  refundId: string;
  status: RefundStatus;
  txHash?: Hash;
  amount: bigint;
  fee: bigint;
  netAmount: bigint;
  timestamp: number;
  error?: string;
}

export interface RefundPolicy {
  maxRefundWindowDays: number;
  refundFeePercent: number;
  minRefundAmount: bigint;
  maxRefundAmount: bigint;
  allowPartialRefunds: boolean;
  requiresApproval: boolean;
  autoApproveThreshold: bigint;
}

// ═══════════════════════════════════════════════════════════════════════════
// ERC20 ABI for transfers
// ═══════════════════════════════════════════════════════════════════════════

const ERC20_ABI = [
  {
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

// ═══════════════════════════════════════════════════════════════════════════
// Refund Service
// ═══════════════════════════════════════════════════════════════════════════

export class RefundService {
  private policy: RefundPolicy;
  private signerPrivateKey: `0x${string}`;
  
  constructor(signerPrivateKey: `0x${string}`, policy?: Partial<RefundPolicy>) {
    this.signerPrivateKey = signerPrivateKey;
    this.policy = {
      maxRefundWindowDays: 30,
      refundFeePercent: 0,
      minRefundAmount: parseUnits('0.01', 6), // 0.01 USDC
      maxRefundAmount: parseUnits('10000', 6), // 10k USDC
      allowPartialRefunds: true,
      requiresApproval: false,
      autoApproveThreshold: parseUnits('100', 6), // Auto-approve under $100
      ...policy,
    };
  }

  /**
   * Process a refund request
   */
  async processRefund(request: RefundRequest): Promise<RefundResult> {
    const refundId = `ref_${Date.now()}_${Math.random().toString(36).slice(2, 11)}`;
    
    try {
      // Validate the request
      await this.validateRefundRequest(request);
      
      // Calculate fees
      const fee = (request.amount * BigInt(this.policy.refundFeePercent)) / 100n;
      const netAmount = request.amount - fee;
      
      // Check if approval is required
      if (this.policy.requiresApproval && request.amount > this.policy.autoApproveThreshold) {
        return {
          refundId,
          status: RefundStatus.PENDING,
          amount: request.amount,
          fee,
          netAmount,
          timestamp: Date.now(),
        };
      }
      
      // Execute the refund
      const txHash = await this.executeRefund(request, netAmount);
      
      return {
        refundId,
        status: RefundStatus.COMPLETED,
        txHash,
        amount: request.amount,
        fee,
        netAmount,
        timestamp: Date.now(),
      };
    } catch (error) {
      return {
        refundId,
        status: RefundStatus.FAILED,
        amount: request.amount,
        fee: 0n,
        netAmount: 0n,
        timestamp: Date.now(),
        error: error instanceof Error ? error.message : 'Refund failed',
      };
    }
  }

  /**
   * Execute the on-chain refund transfer
   */
  private async executeRefund(request: RefundRequest, amount: bigint): Promise<Hash> {
    const chain = this.getChainById(request.chainId);
    const account = privateKeyToAccount(this.signerPrivateKey);
    
    const publicClient = createPublicClient({
      chain,
      transport: http(),
    });
    
    const walletClient = createWalletClient({
      account,
      chain,
      transport: http(),
    });

    // Check balance before transfer
    const balance = await publicClient.readContract({
      address: request.asset,
      abi: ERC20_ABI,
      functionName: 'balanceOf',
      args: [account.address],
    });

    if (balance < amount) {
      throw new Error(`Insufficient balance for refund: ${balance} < ${amount}`);
    }

    // Execute the transfer
    const hash = await walletClient.writeContract({
      address: request.asset,
      abi: ERC20_ABI,
      functionName: 'transfer',
      args: [request.recipient, amount],
    });

    // Wait for confirmation
    await publicClient.waitForTransactionReceipt({ hash });

    return hash;
  }

  /**
   * Validate refund request against policy
   */
  private async validateRefundRequest(request: RefundRequest): Promise<void> {
    // Check amount limits
    if (request.amount < this.policy.minRefundAmount) {
      throw new Error(`Refund amount below minimum: ${request.amount} < ${this.policy.minRefundAmount}`);
    }
    
    if (request.amount > this.policy.maxRefundAmount) {
      throw new Error(`Refund amount exceeds maximum: ${request.amount} > ${this.policy.maxRefundAmount}`);
    }

    // Validate recipient address
    if (!request.recipient || !/^0x[a-fA-F0-9]{40}$/.test(request.recipient)) {
      throw new Error('Invalid recipient address');
    }

    // Validate original transaction exists (in production, verify on-chain)
    if (!request.originalTxHash || !/^0x[a-fA-F0-9]{64}$/.test(request.originalTxHash)) {
      throw new Error('Invalid original transaction hash');
    }
  }

  /**
   * Calculate refund amount after fees
   */
  calculateRefundAmount(grossAmount: bigint): { fee: bigint; netAmount: bigint } {
    const fee = (grossAmount * BigInt(this.policy.refundFeePercent)) / 100n;
    return {
      fee,
      netAmount: grossAmount - fee,
    };
  }

  /**
   * Check if a refund is eligible
   */
  async checkRefundEligibility(
    paymentDate: Date,
    amount: bigint
  ): Promise<{ eligible: boolean; reason?: string }> {
    const daysSincePayment = Math.floor(
      (Date.now() - paymentDate.getTime()) / (1000 * 60 * 60 * 24)
    );

    if (daysSincePayment > this.policy.maxRefundWindowDays) {
      return {
        eligible: false,
        reason: `Refund window expired (${daysSincePayment} days > ${this.policy.maxRefundWindowDays} days)`,
      };
    }

    if (amount < this.policy.minRefundAmount) {
      return {
        eligible: false,
        reason: `Amount below minimum refundable amount`,
      };
    }

    if (amount > this.policy.maxRefundAmount) {
      return {
        eligible: false,
        reason: `Amount exceeds maximum refundable amount`,
      };
    }

    return { eligible: true };
  }

  private getChainById(chainId: number) {
    const chains: Record<number, typeof mainnet> = {
      1: mainnet,
      8453: base,
      42161: arbitrum,
      10: optimism,
    };
    return chains[chainId] || mainnet;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Batch Refund Processing
// ═══════════════════════════════════════════════════════════════════════════

export async function processBatchRefunds(
  service: RefundService,
  requests: RefundRequest[]
): Promise<{
  successful: RefundResult[];
  failed: RefundResult[];
  totalRefunded: bigint;
  totalFees: bigint;
}> {
  const results = await Promise.allSettled(
    requests.map((req) => service.processRefund(req))
  );

  const successful: RefundResult[] = [];
  const failed: RefundResult[] = [];
  let totalRefunded = 0n;
  let totalFees = 0n;

  for (const result of results) {
    if (result.status === 'fulfilled') {
      const refund = result.value;
      if (refund.status === RefundStatus.COMPLETED) {
        successful.push(refund);
        totalRefunded += refund.netAmount;
        totalFees += refund.fee;
      } else {
        failed.push(refund);
      }
    } else {
      failed.push({
        refundId: 'unknown',
        status: RefundStatus.FAILED,
        amount: 0n,
        fee: 0n,
        netAmount: 0n,
        timestamp: Date.now(),
        error: result.reason?.message || 'Unknown error',
      });
    }
  }

  return { successful, failed, totalRefunded, totalFees };
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default RefundService;
