/**
 * @file verification.ts
 * @description On-chain payment verification for x402 protocol
 * @implements payments.ts#L148 TODO: Implement actual on-chain verification
 * @auto-generated by todo-automation
 */

import {
  createPublicClient,
  http,
  parseEventLogs,
  type Address,
  type Hash,
  type Log,
} from 'viem';
import { mainnet, base, arbitrum, optimism, sepolia } from 'viem/chains';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface PaymentVerificationRequest {
  txHash: Hash;
  chainId: number;
  expectedPayer: Address;
  expectedRecipient: Address;
  expectedAmount: bigint;
  expectedAsset: Address;
  maxAgeSeconds?: number;
}

export interface PaymentVerificationResult {
  verified: boolean;
  txHash: Hash;
  blockNumber: bigint;
  blockTimestamp: number;
  payer: Address;
  recipient: Address;
  amount: bigint;
  asset: Address;
  confirmations: number;
  error?: string;
}

export interface TransferEvent {
  from: Address;
  to: Address;
  value: bigint;
  tokenAddress: Address;
}

// ═══════════════════════════════════════════════════════════════════════════
// ERC20 Transfer Event ABI
// ═══════════════════════════════════════════════════════════════════════════

const ERC20_TRANSFER_EVENT = {
  anonymous: false,
  inputs: [
    { indexed: true, name: 'from', type: 'address' },
    { indexed: true, name: 'to', type: 'address' },
    { indexed: false, name: 'value', type: 'uint256' },
  ],
  name: 'Transfer',
  type: 'event',
} as const;

const ERC20_ABI = [ERC20_TRANSFER_EVENT] as const;

// ═══════════════════════════════════════════════════════════════════════════
// Payment Verifier
// ═══════════════════════════════════════════════════════════════════════════

export class PaymentVerifier {
  private clients: Map<number, ReturnType<typeof createPublicClient>> = new Map();

  constructor(rpcUrls?: Record<number, string>) {
    // Initialize clients for common chains
    const defaultChains = [
      { chain: mainnet, id: 1 },
      { chain: base, id: 8453 },
      { chain: arbitrum, id: 42161 },
      { chain: optimism, id: 10 },
      { chain: sepolia, id: 11155111 },
    ];

    for (const { chain, id } of defaultChains) {
      const transport = rpcUrls?.[id] ? http(rpcUrls[id]) : http();
      this.clients.set(id, createPublicClient({ chain, transport }));
    }
  }

  /**
   * Verify a payment transaction on-chain
   */
  async verifyPayment(request: PaymentVerificationRequest): Promise<PaymentVerificationResult> {
    const client = this.clients.get(request.chainId);
    if (!client) {
      return {
        verified: false,
        txHash: request.txHash,
        blockNumber: 0n,
        blockTimestamp: 0,
        payer: request.expectedPayer,
        recipient: request.expectedRecipient,
        amount: 0n,
        asset: request.expectedAsset,
        confirmations: 0,
        error: `Unsupported chain: ${request.chainId}`,
      };
    }

    try {
      // Get transaction receipt
      const receipt = await client.getTransactionReceipt({ hash: request.txHash });
      
      if (receipt.status !== 'success') {
        return {
          verified: false,
          txHash: request.txHash,
          blockNumber: receipt.blockNumber,
          blockTimestamp: 0,
          payer: request.expectedPayer,
          recipient: request.expectedRecipient,
          amount: 0n,
          asset: request.expectedAsset,
          confirmations: 0,
          error: 'Transaction failed',
        };
      }

      // Get block for timestamp
      const block = await client.getBlock({ blockNumber: receipt.blockNumber });
      const blockTimestamp = Number(block.timestamp);

      // Check if transaction is too old
      if (request.maxAgeSeconds) {
        const age = Math.floor(Date.now() / 1000) - blockTimestamp;
        if (age > request.maxAgeSeconds) {
          return {
            verified: false,
            txHash: request.txHash,
            blockNumber: receipt.blockNumber,
            blockTimestamp,
            payer: request.expectedPayer,
            recipient: request.expectedRecipient,
            amount: 0n,
            asset: request.expectedAsset,
            confirmations: 0,
            error: `Transaction too old: ${age}s > ${request.maxAgeSeconds}s`,
          };
        }
      }

      // Get current block for confirmations
      const currentBlock = await client.getBlockNumber();
      const confirmations = Number(currentBlock - receipt.blockNumber);

      // Check if it's a native token transfer
      const transaction = await client.getTransaction({ hash: request.txHash });
      
      if (request.expectedAsset === '0x0000000000000000000000000000000000000000') {
        // Native token transfer
        const isCorrectPayer = transaction.from.toLowerCase() === request.expectedPayer.toLowerCase();
        const isCorrectRecipient = transaction.to?.toLowerCase() === request.expectedRecipient.toLowerCase();
        const isCorrectAmount = transaction.value >= request.expectedAmount;

        return {
          verified: isCorrectPayer && isCorrectRecipient && isCorrectAmount,
          txHash: request.txHash,
          blockNumber: receipt.blockNumber,
          blockTimestamp,
          payer: transaction.from,
          recipient: transaction.to || request.expectedRecipient,
          amount: transaction.value,
          asset: request.expectedAsset,
          confirmations,
          error: !isCorrectPayer ? 'Wrong payer' : 
                 !isCorrectRecipient ? 'Wrong recipient' : 
                 !isCorrectAmount ? 'Insufficient amount' : undefined,
        };
      }

      // ERC20 token transfer - parse logs
      const transferLogs = parseEventLogs({
        abi: ERC20_ABI,
        logs: receipt.logs as Log[],
        eventName: 'Transfer',
      });

      // Find matching transfer
      const matchingTransfer = transferLogs.find((log) => {
        const args = log.args as { from: Address; to: Address; value: bigint };
        return (
          log.address.toLowerCase() === request.expectedAsset.toLowerCase() &&
          args.from.toLowerCase() === request.expectedPayer.toLowerCase() &&
          args.to.toLowerCase() === request.expectedRecipient.toLowerCase() &&
          args.value >= request.expectedAmount
        );
      });

      if (!matchingTransfer) {
        return {
          verified: false,
          txHash: request.txHash,
          blockNumber: receipt.blockNumber,
          blockTimestamp,
          payer: request.expectedPayer,
          recipient: request.expectedRecipient,
          amount: 0n,
          asset: request.expectedAsset,
          confirmations,
          error: 'No matching transfer found in transaction logs',
        };
      }

      const args = matchingTransfer.args as { from: Address; to: Address; value: bigint };

      return {
        verified: true,
        txHash: request.txHash,
        blockNumber: receipt.blockNumber,
        blockTimestamp,
        payer: args.from,
        recipient: args.to,
        amount: args.value,
        asset: matchingTransfer.address,
        confirmations,
      };
    } catch (error) {
      return {
        verified: false,
        txHash: request.txHash,
        blockNumber: 0n,
        blockTimestamp: 0,
        payer: request.expectedPayer,
        recipient: request.expectedRecipient,
        amount: 0n,
        asset: request.expectedAsset,
        confirmations: 0,
        error: error instanceof Error ? error.message : 'Verification failed',
      };
    }
  }

  /**
   * Verify multiple payments in batch
   */
  async verifyBatch(
    requests: PaymentVerificationRequest[]
  ): Promise<PaymentVerificationResult[]> {
    return Promise.all(requests.map((req) => this.verifyPayment(req)));
  }

  /**
   * Wait for payment confirmation
   */
  async waitForPayment(
    request: PaymentVerificationRequest,
    options?: {
      minConfirmations?: number;
      timeoutMs?: number;
      pollIntervalMs?: number;
    }
  ): Promise<PaymentVerificationResult> {
    const minConfirmations = options?.minConfirmations || 1;
    const timeoutMs = options?.timeoutMs || 120000; // 2 minutes
    const pollIntervalMs = options?.pollIntervalMs || 2000;

    const startTime = Date.now();

    while (Date.now() - startTime < timeoutMs) {
      const result = await this.verifyPayment(request);
      
      if (result.verified && result.confirmations >= minConfirmations) {
        return result;
      }

      if (result.error && !result.error.includes('pending')) {
        return result; // Return if there's a definitive error
      }

      await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
    }

    return {
      verified: false,
      txHash: request.txHash,
      blockNumber: 0n,
      blockTimestamp: 0,
      payer: request.expectedPayer,
      recipient: request.expectedRecipient,
      amount: 0n,
      asset: request.expectedAsset,
      confirmations: 0,
      error: 'Timeout waiting for payment confirmation',
    };
  }

  /**
   * Get all transfers for an address
   */
  async getTransfers(
    address: Address,
    chainId: number,
    options?: {
      fromBlock?: bigint;
      toBlock?: bigint;
      tokens?: Address[];
    }
  ): Promise<TransferEvent[]> {
    const client = this.clients.get(chainId);
    if (!client) return [];

    const fromBlock = options?.fromBlock || 'earliest';
    const toBlock = options?.toBlock || 'latest';

    try {
      // Get incoming transfers
      const incomingLogs = await client.getLogs({
        event: ERC20_TRANSFER_EVENT,
        args: { to: address },
        fromBlock,
        toBlock,
        address: options?.tokens,
      });

      // Get outgoing transfers
      const outgoingLogs = await client.getLogs({
        event: ERC20_TRANSFER_EVENT,
        args: { from: address },
        fromBlock,
        toBlock,
        address: options?.tokens,
      });

      const allLogs = [...incomingLogs, ...outgoingLogs];

      return allLogs.map((log) => ({
        from: (log.args as { from: Address }).from,
        to: (log.args as { to: Address }).to,
        value: (log.args as { value: bigint }).value,
        tokenAddress: log.address,
      }));
    } catch {
      return [];
    }
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Convenience Functions
// ═══════════════════════════════════════════════════════════════════════════

const defaultVerifier = new PaymentVerifier();

export async function verifyPayment(
  request: PaymentVerificationRequest
): Promise<PaymentVerificationResult> {
  return defaultVerifier.verifyPayment(request);
}

export async function waitForPayment(
  request: PaymentVerificationRequest,
  options?: {
    minConfirmations?: number;
    timeoutMs?: number;
  }
): Promise<PaymentVerificationResult> {
  return defaultVerifier.waitForPayment(request, options);
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default PaymentVerifier;
