# @file .gitbook.yaml
# @author nich.xbt
# @copyright (c) 2026 nichxbt
# @repository universal-crypto-mcp

root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md


# universal-crypto-mcp © nirholas