/**
 * @file sweep.ts
 * @description Token sweeping and consolidation implementation
 * @implements workers.ts#L49, sweep.ts#L104, sweep.ts#L220 TODOs
 * @auto-generated by todo-automation
 */

import {
  createPublicClient,
  createWalletClient,
  http,
  parseUnits,
  formatUnits,
  type Address,
  type Hash,
  type Chain,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { mainnet, base, arbitrum, optimism, polygon } from 'viem/chains';

// ═══════════════════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════════════════

export interface SweepConfig {
  sourceWallets: Address[];
  destinationWallet: Address;
  tokens: TokenConfig[];
  chainId: number;
  minSweepValue: bigint;
  maxGasPrice: bigint;
  batchSize: number;
  retryAttempts: number;
  gasBuffer: number; // Percentage buffer for gas estimation
}

export interface TokenConfig {
  address: Address;
  symbol: string;
  decimals: number;
  minBalance: bigint;
}

export interface SweepResult {
  sweepId: string;
  sourceWallet: Address;
  destinationWallet: Address;
  transfers: TransferResult[];
  totalValueUsd: number;
  gasUsed: bigint;
  gasPrice: bigint;
  timestamp: number;
  status: 'completed' | 'partial' | 'failed';
}

export interface TransferResult {
  token: Address;
  amount: bigint;
  txHash?: Hash;
  status: 'success' | 'failed' | 'skipped';
  error?: string;
}

export interface ConsolidationPlan {
  sourceWallets: Address[];
  destination: Address;
  estimatedTransfers: number;
  estimatedGas: bigint;
  tokens: Array<{
    address: Address;
    symbol: string;
    totalAmount: bigint;
    walletBalances: Map<Address, bigint>;
  }>;
}

// ═══════════════════════════════════════════════════════════════════════════
// ABIs
// ═══════════════════════════════════════════════════════════════════════════

const ERC20_ABI = [
  {
    inputs: [{ name: 'account', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', type: 'bool' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'decimals',
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'symbol',
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
] as const;

// ═══════════════════════════════════════════════════════════════════════════
// Sweep Service
// ═══════════════════════════════════════════════════════════════════════════

export class SweepService {
  private chain: Chain;
  private publicClient: ReturnType<typeof createPublicClient>;

  constructor(chainId: number, rpcUrl?: string) {
    this.chain = this.getChainById(chainId);
    this.publicClient = createPublicClient({
      chain: this.chain,
      transport: http(rpcUrl),
    });
  }

  /**
   * Plan consolidation before execution
   */
  async planConsolidation(
    sourceWallets: Address[],
    destination: Address,
    tokens: Address[]
  ): Promise<ConsolidationPlan> {
    const tokenDetails: ConsolidationPlan['tokens'] = [];

    for (const tokenAddress of tokens) {
      const walletBalances = new Map<Address, bigint>();
      let totalAmount = 0n;

      // Get token info
      const [symbol, decimals] = await Promise.all([
        this.publicClient.readContract({
          address: tokenAddress,
          abi: ERC20_ABI,
          functionName: 'symbol',
        }),
        this.publicClient.readContract({
          address: tokenAddress,
          abi: ERC20_ABI,
          functionName: 'decimals',
        }),
      ]);

      // Get balances from all source wallets
      for (const wallet of sourceWallets) {
        const balance = await this.publicClient.readContract({
          address: tokenAddress,
          abi: ERC20_ABI,
          functionName: 'balanceOf',
          args: [wallet],
        });

        if (balance > 0n) {
          walletBalances.set(wallet, balance);
          totalAmount += balance;
        }
      }

      if (totalAmount > 0n) {
        tokenDetails.push({
          address: tokenAddress,
          symbol,
          totalAmount,
          walletBalances,
        });
      }
    }

    // Estimate gas
    const estimatedTransfers = tokenDetails.reduce(
      (sum, t) => sum + t.walletBalances.size,
      0
    );
    const estimatedGas = BigInt(estimatedTransfers) * 65000n; // ~65k gas per ERC20 transfer

    return {
      sourceWallets,
      destination,
      estimatedTransfers,
      estimatedGas,
      tokens: tokenDetails,
    };
  }

  /**
   * Execute sweep from a single wallet
   */
  async sweepWallet(
    sourcePrivateKey: `0x${string}`,
    destination: Address,
    tokens: TokenConfig[],
    options?: {
      minBalance?: bigint;
      maxGasPrice?: bigint;
    }
  ): Promise<SweepResult> {
    const sweepId = `swp_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    const account = privateKeyToAccount(sourcePrivateKey);
    const transfers: TransferResult[] = [];

    const walletClient = createWalletClient({
      account,
      chain: this.chain,
      transport: http(),
    });

    // Check gas price
    const gasPrice = await this.publicClient.getGasPrice();
    if (options?.maxGasPrice && gasPrice > options.maxGasPrice) {
      return {
        sweepId,
        sourceWallet: account.address,
        destinationWallet: destination,
        transfers: [],
        totalValueUsd: 0,
        gasUsed: 0n,
        gasPrice,
        timestamp: Date.now(),
        status: 'failed',
      };
    }

    // Process each token
    let totalGasUsed = 0n;

    for (const token of tokens) {
      try {
        // Get balance
        const balance = await this.publicClient.readContract({
          address: token.address,
          abi: ERC20_ABI,
          functionName: 'balanceOf',
          args: [account.address],
        });

        const minBalance = options?.minBalance || token.minBalance;
        
        if (balance <= minBalance) {
          transfers.push({
            token: token.address,
            amount: balance,
            status: 'skipped',
          });
          continue;
        }

        // Execute transfer
        const hash = await walletClient.writeContract({
          address: token.address,
          abi: ERC20_ABI,
          functionName: 'transfer',
          args: [destination, balance],
        });

        const receipt = await this.publicClient.waitForTransactionReceipt({ hash });
        totalGasUsed += receipt.gasUsed;

        transfers.push({
          token: token.address,
          amount: balance,
          txHash: hash,
          status: 'success',
        });
      } catch (error) {
        transfers.push({
          token: token.address,
          amount: 0n,
          status: 'failed',
          error: error instanceof Error ? error.message : 'Transfer failed',
        });
      }
    }

    // Sweep native token (ETH)
    try {
      const ethBalance = await this.publicClient.getBalance({
        address: account.address,
      });
      
      // Reserve gas for the transfer
      const gasLimit = 21000n;
      const gasCost = gasLimit * gasPrice;
      const transferAmount = ethBalance - gasCost - parseUnits('0.001', 18); // Keep small buffer

      if (transferAmount > 0n) {
        const hash = await walletClient.sendTransaction({
          to: destination,
          value: transferAmount,
        });

        const receipt = await this.publicClient.waitForTransactionReceipt({ hash });
        totalGasUsed += receipt.gasUsed;

        transfers.push({
          token: '0x0000000000000000000000000000000000000000' as Address,
          amount: transferAmount,
          txHash: hash,
          status: 'success',
        });
      }
    } catch (error) {
      // Native transfer failed, continue
    }

    const successCount = transfers.filter((t) => t.status === 'success').length;
    const status =
      successCount === transfers.length
        ? 'completed'
        : successCount > 0
        ? 'partial'
        : 'failed';

    return {
      sweepId,
      sourceWallet: account.address,
      destinationWallet: destination,
      transfers,
      totalValueUsd: 0, // Would need price oracle
      gasUsed: totalGasUsed,
      gasPrice,
      timestamp: Date.now(),
      status,
    };
  }

  /**
   * Execute batch sweep from multiple wallets
   */
  async batchSweep(
    walletKeys: `0x${string}`[],
    destination: Address,
    tokens: TokenConfig[],
    options?: {
      batchSize?: number;
      delayMs?: number;
    }
  ): Promise<SweepResult[]> {
    const results: SweepResult[] = [];
    const batchSize = options?.batchSize || 5;
    const delayMs = options?.delayMs || 1000;

    for (let i = 0; i < walletKeys.length; i += batchSize) {
      const batch = walletKeys.slice(i, i + batchSize);
      
      const batchResults = await Promise.all(
        batch.map((key) => this.sweepWallet(key, destination, tokens))
      );
      
      results.push(...batchResults);

      // Delay between batches to avoid rate limiting
      if (i + batchSize < walletKeys.length) {
        await new Promise((resolve) => setTimeout(resolve, delayMs));
      }
    }

    return results;
  }

  /**
   * Track transaction status
   */
  async trackTransaction(txHash: Hash): Promise<{
    status: 'pending' | 'confirmed' | 'failed';
    confirmations: number;
    gasUsed?: bigint;
  }> {
    try {
      const receipt = await this.publicClient.getTransactionReceipt({ hash: txHash });
      const block = await this.publicClient.getBlockNumber();
      
      return {
        status: receipt.status === 'success' ? 'confirmed' : 'failed',
        confirmations: Number(block - receipt.blockNumber),
        gasUsed: receipt.gasUsed,
      };
    } catch {
      return {
        status: 'pending',
        confirmations: 0,
      };
    }
  }

  private getChainById(chainId: number): Chain {
    const chains: Record<number, Chain> = {
      1: mainnet,
      8453: base,
      42161: arbitrum,
      10: optimism,
      137: polygon,
    };
    return chains[chainId] || mainnet;
  }
}

// ═══════════════════════════════════════════════════════════════════════════
// Quote Generation
// ═══════════════════════════════════════════════════════════════════════════

export interface SweepQuote {
  sourceWallets: Address[];
  destination: Address;
  estimatedGas: bigint;
  estimatedGasPrice: bigint;
  estimatedCostUsd: number;
  tokens: Array<{
    address: Address;
    symbol: string;
    amount: bigint;
    valueUsd: number;
  }>;
  totalValueUsd: number;
  netValueUsd: number;
}

export async function generateSweepQuote(
  chainId: number,
  sourceWallets: Address[],
  destination: Address,
  tokens: Address[]
): Promise<SweepQuote> {
  const service = new SweepService(chainId);
  const plan = await service.planConsolidation(sourceWallets, destination, tokens);

  // In production, fetch actual prices
  const mockPriceUsd = 1.0;

  const tokenDetails = plan.tokens.map((t) => ({
    address: t.address,
    symbol: t.symbol,
    amount: t.totalAmount,
    valueUsd: Number(formatUnits(t.totalAmount, 18)) * mockPriceUsd,
  }));

  const totalValueUsd = tokenDetails.reduce((sum, t) => sum + t.valueUsd, 0);
  const estimatedGasPrice = parseUnits('30', 9); // 30 gwei
  const estimatedCostUsd = Number(formatUnits(plan.estimatedGas * estimatedGasPrice, 18)) * 2500; // ETH price

  return {
    sourceWallets,
    destination,
    estimatedGas: plan.estimatedGas,
    estimatedGasPrice,
    estimatedCostUsd,
    tokens: tokenDetails,
    totalValueUsd,
    netValueUsd: totalValueUsd - estimatedCostUsd,
  };
}

// ═══════════════════════════════════════════════════════════════════════════
// Exports
// ═══════════════════════════════════════════════════════════════════════════

export default SweepService;
